/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/composed-chart/composed-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { ComposedChart } = scope;
  return (
<ComposedChart
title="Revenue and margin"
labels={["Q1", "Q2", "Q3", "Q4"]}
series={[
  { label: "Revenue", values: [420, 510, 480, 620] },
  { label: "Margin", values: [110, 170, 150, 240], line: true },
]}
/>
  );
}
