/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/stacked-bar/stacked-bar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, StackedBar } = scope;
  return (
<Card padded>
  <StackedBar
    segments={[
      { label: "Direct", value: 42 },
      { label: "Organic search", value: 28 },
      { label: "Social", value: 18 },
      { label: "Referral", value: 12 }
    ]}
  />
</Card>
  );
}
