/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/stacked-bar/stacked-bar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Container, StackedBar } = scope;
  return (
<Container xl>
  <Card padded>
    <StackedBar
      tall
      subtle
      track
      hideLegend
      label="Verified identities"
      segments={[
        { label: "Verified", value: 1502 },
        { label: "Unverified", value: 345 }
      ]}
    />
  </Card>
</Container>
  );
}
