/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/stacked-bar/stacked-bar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { StackedBar } = scope;
  return (
<StackedBar
  track
  label="Courier queue"
  segments={[
    { label: "Sent", value: 0 },
    { label: "Queued", value: 0 }
  ]}
/>
  );
}
