import { expect, test } from "bun:test";
import { annotateFrames, moduleOffset, parseMappings, printed, splitSections } from "../scripts/soak-crash-dumps.mjs";

// The shape gdb 15 prints for a Firefox core (addresses shortened to one module's worth).
const GDB = `[New LWP 4201]
[New LWP 4207]
Core was generated by \`/home/runner/.cache/ms-playwright/firefox-1551/firefox/firefox -no-remote -headless'.
Program terminated with signal SIGSEGV, Segmentation fault.

@@section mappings
Mapped address spaces:

          Start Addr           End Addr       Size     Offset objfile
      0x5601a0000000     0x5601a0010000    0x10000        0x0 /home/runner/.cache/ms-playwright/firefox-1551/firefox/firefox
      0x7f3c50000000     0x7f3c52000000  0x2000000        0x0 /home/runner/.cache/ms-playwright/firefox-1551/firefox/libxul.so
      0x7f3c52000000     0x7f3c58000000  0x6000000  0x2000000 /home/runner/.cache/ms-playwright/firefox-1551/firefox/libxul.so
      0x7f3c60000000     0x7f3c60028000    0x28000        0x0 /usr/lib/x86_64-linux-gnu/libc.so.6

@@section signal
$1 = 11

@@section code
$2 = 1

@@section reason
No symbol "gMozCrashReason" in current context.

@@section crashing
#0  0x00007f3c52a3c10d in ?? () from /home/runner/.cache/ms-playwright/firefox-1551/firefox/libxul.so
#1  0x00007f3c60011f00 in __libc_start_call_main (...) at ../sysdeps/nptl/libc_start_call_main.h:58
#2  0x0000000000001234 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
`;

test("splitSections files each command's answer under its marker, and nothing from before the first", () => {
  const sections = splitSections(GDB);
  expect(Object.keys(sections)).toEqual(["mappings", "signal", "code", "reason", "crashing"]);
  expect(sections.signal).toBe("$1 = 11");
  expect(sections.reason).toBe('No symbol "gMozCrashReason" in current context.');
});

test("printed reads gdb's answer and is null for an error", () => {
  const sections = splitSections(GDB);
  expect(printed(sections.signal)).toBe("11");
  expect(printed(sections.reason)).toBeNull();
  expect(printed('$7 = 0x7f3c55000000 "MOZ_CRASH(IPC FatalError in the parent process!)"')).toBe('0x7f3c55000000 "MOZ_CRASH(IPC FatalError in the parent process!)"');
  expect(printed(undefined)).toBeNull();
});

test("parseMappings keeps every mapped file, with or without a permissions column", () => {
  const mappings = parseMappings(splitSections(GDB).mappings);
  expect(mappings.map((mapping) => mapping.file.split("/").pop())).toEqual(["firefox", "libxul.so", "libxul.so", "libc.so.6"]);
  expect(parseMappings("      0x400000           0x401000     0x1000        0x0  r-xp   /usr/bin/sleep")).toEqual([
    { start: 0x400000n, end: 0x401000n, file: "/usr/bin/sleep" },
  ]);
});

test("moduleOffset measures from the module's lowest mapping, across its later segments", () => {
  const mappings = parseMappings(splitSections(GDB).mappings);
  expect(moduleOffset(0x7f3c52a3c10dn, mappings)).toBe("libxul.so+0x2a3c10d");
  expect(moduleOffset(0x7f3c50000010n, mappings)).toBe("libxul.so+0x10");
  expect(moduleOffset(0x1234n, mappings)).toBeNull();
});

test("annotateFrames places each frame it can and leaves the rest as gdb wrote them", () => {
  const sections = splitSections(GDB);
  const lines = annotateFrames(sections.crashing, parseMappings(sections.mappings)).split("\n");
  expect(lines[0]).toEndWith("from /home/runner/.cache/ms-playwright/firefox-1551/firefox/libxul.so  [libxul.so+0x2a3c10d]");
  expect(lines[1]).toEndWith("libc_start_call_main.h:58  [libc.so.6+0x11f00]");
  expect(lines[2]).toBe("#2  0x0000000000001234 in ?? ()");
  expect(lines[3]).toStartWith("Backtrace stopped");
});
