/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/treemap/treemap.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Treemap } = scope;
  return (
<Treemap
title="Storage by service"
data={[
  { label: "Media", value: 620 },
  { label: "Backups", value: 340 },
  { label: "Logs", value: 180 },
]}
/>
  );
}
