/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/treemap/treemap.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Treemap } = scope;
  return (
<Treemap
  compact
  data={[
    { label: "Chrome", value: 61 },
    { label: "Safari", value: 24 },
    { label: "Edge", value: 8 },
    { label: "Firefox", value: 5 },
    { label: "Other", value: 2 }
  ]}
/>
  );
}
