/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/divider/divider.md
import type { ComponentDocs } from "../../../scope";
import e_atoms_divider_example_0 from "./example-0";
import e_atoms_divider_example_1 from "./example-1";
import e_atoms_divider_example_2 from "./example-2";
import e_atoms_divider_example_3 from "./example-3";
import e_atoms_divider_dont_0_do from "./dont-0-do";
import e_atoms_divider_dont_0_dont from "./dont-0-dont";
import e_atoms_divider_dont_1_do from "./dont-1-do";
import e_atoms_divider_dont_1_dont from "./dont-1-dont";
import e_atoms_divider_dont_2_do from "./dont-2-do";
import e_atoms_divider_dont_2_dont from "./dont-2-dont";
import e_atoms_divider_dont_3_do from "./dont-3-do";
import e_atoms_divider_dont_3_dont from "./dont-3-dont";

export const docs: ComponentDocs = {
  dir: "divider",
  category: "atoms",
  examples: [
    { label: "Default", code: "<Column>\n  <Typography>Profile</Typography>\n  <Divider />\n  <Typography>Account</Typography>\n</Column>", render: e_atoms_divider_example_0 },
    { label: "Vertical", code: "<Row>\n  <Typography>Edit</Typography>\n  <Divider vertical />\n  <Typography>Delete</Typography>\n</Row>", render: e_atoms_divider_example_1 },
    { label: "Label", code: "<Divider>Or continue with</Divider>", render: e_atoms_divider_example_2 },
    { label: "Action", code: "<Divider>\n  <Button ghost small>Show more</Button>\n</Divider>", render: e_atoms_divider_example_3 },
  ],
  donts: [
    { title: "Plain", do: { caption: "Click a row: group with spacing and reserve a divider for a real break like Sign out.", code: "<Column tight>\n  <Typography small>Profile</Typography>\n  <Typography small>Account</Typography>\n  <Typography small>Notifications</Typography>\n  <Divider />\n  <Typography small>Sign out</Typography>\n</Column>", render: e_atoms_divider_dont_0_do }, dont: { caption: "Click a row: a divider between every one is noise that competes with the content.", code: "<View>\n  <Text style={{ borderRadius: 6, paddingHorizontal: 8, paddingVertical: 6, fontSize: 14, lineHeight: 20 }}>Profile</Text>\n  <Divider />\n  <Text style={{ borderRadius: 6, paddingHorizontal: 8, paddingVertical: 6, fontSize: 14, lineHeight: 20 }}>Account</Text>\n  <Divider />\n  <Text style={{ borderRadius: 6, paddingHorizontal: 8, paddingVertical: 6, fontSize: 14, lineHeight: 20 }}>Notifications</Text>\n  <Divider />\n  <Text style={{ borderRadius: 6, paddingHorizontal: 8, paddingVertical: 6, fontSize: 14, lineHeight: 20 }}>Billing</Text>\n</View>", render: e_atoms_divider_dont_0_dont } },
    { title: "With label", do: { caption: "Click a provider: keep the label to a few words and let the buttons carry the options.", code: "<Column snug>\n  <Button primary block>Sign in</Button>\n  <Divider>or continue with</Divider>\n  <Row snug>\n    <Column fill>\n      <Button outline block>Google</Button>\n    </Column>\n    <Column fill>\n      <Button outline block>GitHub</Button>\n    </Column>\n  </Row>\n</Column>", render: e_atoms_divider_dont_1_do }, dont: { caption: "Click Sign in: a full sentence in the label divider buries the choice.", code: "<View style={{ width: 320, maxWidth: \"100%\", flexDirection: \"column\", gap: 8 }}>\n  <Button primary block>Sign in</Button>\n  <Divider>or continue with one of your previously linked third-party accounts</Divider>\n</View>", render: e_atoms_divider_dont_1_dont } },
    { title: "With action", do: { caption: "Click Show more: the button toggles its label and reveals the rest.", code: "<Column snug>\n  <Typography small muted>Logged in from 2 new devices · 3 more entries</Typography>\n  <Divider>\n    <Button ghost small>Show less</Button>\n  </Divider>\n</Column>", render: e_atoms_divider_dont_2_do }, dont: { caption: "Click the button: an action divider that does nothing is just decoration.", code: "<Divider>\n  <Button ghost small>Show more</Button>\n</Divider>", render: e_atoms_divider_dont_2_dont } },
    { title: "Vertical", do: { caption: "Click an action: the vertical rule separates inline actions in a row.", code: "<Row alignCenter cozy>\n  <Typography small>Edit</Typography>\n  <Divider vertical style={{ height: 16 }} />\n  <Typography small>Delete</Typography>\n  <Divider vertical style={{ height: 16 }} />\n  <Typography small>Share</Typography>\n</Row>", render: e_atoms_divider_dont_3_do }, dont: { caption: "Click an action: a vertical rule between stacked items reads as a glitch.", code: "<View style={{ flexDirection: \"column\", alignItems: \"flex-start\", gap: 8 }}>\n  <Text style={{ fontSize: 14, lineHeight: 20 }}>Edit</Text>\n  <Divider vertical style={{ height: 16 }} />\n  <Text style={{ fontSize: 14, lineHeight: 20 }}>Delete</Text>\n</View>", render: e_atoms_divider_dont_3_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"DividerProps","props":[{"name":"children","type":"ReactNode","required":false,"description":"Optional middle content. With children, a horizontal divider renders a flanking-line + centered-label row (the \"with label\" / \"with action\" patterns). A string renders as muted label text; arbitrary nodes (e.g. a button) render as-is for the action pattern. Ignored when `vertical`."},{"name":"horizontal","type":"boolean","required":false,"description":"Orientation (pick one; default is horizontal)."},{"name":"vertical","type":"boolean","required":false,"description":"Orientation (pick one; default is horizontal)."},{"name":"soft","type":"boolean","required":false,"description":"Emphasis (pick one; default tracks the border token)."},{"name":"strong","type":"boolean","required":false,"description":"Emphasis (pick one; default tracks the border token)."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
