/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/divider/divider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Divider, Typography, Column, Container } = scope;
  return (
<Container xs>
  <Column snug>
    <Typography small muted>Logged in from 2 new devices · 3 more entries</Typography>
    <Divider>
      <Button ghost small>Show less</Button>
    </Divider>
  </Column>
</Container>
  );
}
