/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/divider/divider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Divider, Row, Column, Container } = scope;
  return (
<Container xs>
  <Column snug>
    <Button primary block>Sign in</Button>
    <Divider>or continue with</Divider>
    <Row snug>
      <Column fill>
        <Button outline block>Google</Button>
      </Column>
      <Column fill>
        <Button outline block>GitHub</Button>
      </Column>
    </Row>
  </Column>
</Container>
  );
}
