/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/divider/divider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Divider, Typography, Column, Container } = scope;
  return (
<Container xs>
  <Column snug>
    <Typography small>Profile</Typography>
    <Divider />
    <Typography small>Account</Typography>
  </Column>
</Container>
  );
}
