/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/divider/divider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Card, Divider, Typography, Column, Container } = scope;
  return (
<Container xs>
  <Column cozy>
    <Column snug>
      <Card padded>
        <Typography small>Ada commented on the draft</Typography>
      </Card>
      <Card padded>
        <Typography small>Grace approved the request</Typography>
      </Card>
    </Column>
    <Divider>
      <Button ghost small>Show more</Button>
    </Divider>
  </Column>
</Container>
  );
}
