/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/divider/divider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Divider, Typography, Row } = scope;
  return (
<Row>
  <Typography>Edit</Typography>
  <Divider vertical />
  <Typography>Delete</Typography>
</Row>
  );
}
