/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/switch/switch.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Switch, Column, Container } = scope;
  return (
<Container xxs>
  <Column cozy alignStart>
    <Switch defaultChecked>Auto-save drafts</Switch>
    <Button destructive small>Delete account…</Button>
  </Column>
</Container>
  );
}
