/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/switch/switch.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Switch } = scope;
  return (
<Switch disabled>Available to chat</Switch>
  );
}
