/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/switch/switch.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Switch, Column } = scope;
  return (
<Column relaxed>
  <Switch defaultChecked description="Show your availability to teammates.">Available to chat</Switch>
  <Switch defaultChecked>Sound effects</Switch>
  <Switch>Weekly digest</Switch>
  <Switch defaultChecked>Push notifications</Switch>
</Column>
  );
}
