/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/code-block/code-block.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { CodeBlock, Typography, Column, Container } = scope;
  return (
<Container sm>
  <Column snug>
    <Typography body>Run the setup command:</Typography>
    <CodeBlock code={`npm install @nannier-com/canvas
  npm run build`} />
  </Column>
</Container>
  );
}
