/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/code-block/code-block.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { CodeBlock } = scope;
  return (
<CodeBlock
  tabs={[
    { label: "npm", code: "npm install @ionizeio/canvas" },
    { label: "yarn", code: "yarn add @ionizeio/canvas" },
    { label: "bun", code: "bun add @ionizeio/canvas" },
  ]}
/>
  );
}
