/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/code-block/code-block.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, CodeBlock } = scope;
  return (
<CodeBlock
  collapsible
  collapsedLines={3}
  language="ts"
  code={`export const tokens = {
  primary: "#6366f1",
  radius: 8,
  border: "#e4e4e7",
  muted: "#f4f4f5",
};`}
/>
  );
}
