/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/code-block/code-block.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { CodeBlock } = scope;
  return (
<CodeBlock inline language="bash" code="npm install" />
  );
}
