/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/service-health-list/service-health-list.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { ServiceHealthList } = scope;
  return (
<ServiceHealthList
title="System status"
items={[
  { label: "API", detail: "99.98%" },
  { label: "Webhooks", detail: "97.10%", down: true },
]}
/>
  );
}
