/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/service-health-list/service-health-list.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, ServiceHealthList } = scope;
  return (
<Card>
  <ServiceHealthList
    plain
    items={[
      { label: "API", detail: "operational" },
      { label: "Dashboard", detail: "degraded", degraded: true }
    ]}
  />
</Card>
  );
}
