/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/service-health-list/service-health-list.md
import type { ComponentDocs } from "../../../scope";
import e_charts_service_health_list_example_0 from "./example-0";
import e_charts_service_health_list_example_1 from "./example-1";
import e_charts_service_health_list_example_2 from "./example-2";
import e_charts_service_health_list_example_3 from "./example-3";
import e_charts_service_health_list_dont_0_do from "./dont-0-do";
import e_charts_service_health_list_dont_0_dont from "./dont-0-dont";

export const docs: ComponentDocs = {
  dir: "service-health-list",
  category: "charts",
  examples: [
    { label: "Default", code: "<ServiceHealthList\n  title=\"System status\"\n  items={[\n    { label: \"API\", detail: \"99.98%\", periods: Array.from({ length: 45 }, () => ({})) },\n    { label: \"Dashboard\", detail: \"99.92%\", periods: Array.from({ length: 45 }, (_, i) => (i === 30 ? { degraded: true } : {})), degraded: true },\n    { label: \"Webhooks\", detail: \"97.10%\", periods: Array.from({ length: 45 }, (_, i) => (i > 40 ? { down: true } : {})), down: true }\n  ]}\n/>", render: e_charts_service_health_list_example_0 },
    { label: "Compact", code: "<ServiceHealthList\n  compact\n  items={[\n    { label: \"API\", detail: \"99.98%\" },\n    { label: \"Dashboard\", detail: \"99.92%\", degraded: true },\n    { label: \"Webhooks\", detail: \"97.10%\", down: true }\n  ]}\n/>", render: e_charts_service_health_list_example_1 },
    { label: "Drill-in rows", code: "<ServiceHealthList\n  onPressItem={() => {}}\n  items={[\n    { label: \"API\", detail: \"99.98%\" },\n    { label: \"Search\", detail: \"99.95%\" },\n    { label: \"Exports\", detail: \"99.80%\", degraded: true }\n  ]}\n/>", render: e_charts_service_health_list_example_2 },
    { label: "Plain, inside a card", code: "<Card>\n  <ServiceHealthList\n    plain\n    items={[\n      { label: \"API\", detail: \"operational\" },\n      { label: \"Dashboard\", detail: \"degraded\", degraded: true }\n    ]}\n  />\n</Card>", render: e_charts_service_health_list_example_3 },
  ],
  donts: [
    { title: "ServiceHealthList", do: { caption: "One row per service, with the status carried by the dot, the composed accessible name, and the embedded strip.", code: "<ServiceHealthList\ntitle=\"System status\"\nitems={[\n  { label: \"API\", detail: \"99.98%\" },\n  { label: \"Webhooks\", detail: \"97.10%\", down: true },\n]}\n/>", render: e_charts_service_health_list_dont_0_do }, dont: { caption: "A hand-rolled status row splits the tap target and loses the status from assistive tech.", code: "<View style={{ borderRadius: 8, borderWidth: 1, borderColor: tokens.border, backgroundColor: tokens.card, padding: 20, maxWidth: 480, gap: 8 }}>\n  <View style={{ flexDirection: \"row\", alignItems: \"center\", gap: 8 }}>\n    <View style={{ width: 8, height: 8, borderRadius: 999, backgroundColor: \"green\" }} />\n    <Text>API</Text>\n  </View>\n</View>", render: e_charts_service_health_list_dont_0_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"ServiceHealthListProps","props":[{"name":"items","type":"ServiceHealthItem[]","required":true,"description":"The services to render, in order."},{"name":"title","type":"string","required":false,"description":"Optional heading shown above the rows."},{"name":"compact","type":"boolean","required":false,"description":"Density (omit for the default rows with embedded strips)."},{"name":"plain","type":"boolean","required":false,"description":"Strip the card surface for nesting inside an existing card (mirrors Stats)."},{"name":"onPressItem","type":"(index: number) => void","required":false,"description":"Rows become tappable drill-in targets (open the service) when set."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
