/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/funnel-chart/funnel-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, FunnelChart } = scope;
  return (
<Container lg>
  <FunnelChart
  stages={[
    { label: "Visits", value: 4200 },
    { label: "Signups", value: 12400 },
  ]}
/>
</Container>
  );
}
