/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/funnel-chart/funnel-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { FunnelChart } = scope;
  return (
<FunnelChart
title="Signup funnel"
stages={[
  { label: "Visits", value: 12400 },
  { label: "Signups", value: 4200 },
  { label: "Paid", value: 480 },
]}
/>
  );
}
