/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/funnel-chart/funnel-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { FunnelChart } = scope;
  return (
<FunnelChart
compact
defaultSelected={1}
stages={[
  { label: "Leads", value: 900 },
  { label: "Qualified", value: 340 },
  { label: "Closed", value: 120 },
]}
/>
  );
}
