/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/funnel-chart/funnel-chart.md
import type { ComponentDocs } from "../../../scope";
import e_charts_funnel_chart_example_0 from "./example-0";
import e_charts_funnel_chart_example_1 from "./example-1";
import e_charts_funnel_chart_example_2 from "./example-2";
import e_charts_funnel_chart_dont_0_do from "./dont-0-do";
import e_charts_funnel_chart_dont_0_dont from "./dont-0-dont";

export const docs: ComponentDocs = {
  dir: "funnel-chart",
  category: "charts",
  examples: [
    { label: "Default", code: "<FunnelChart\n  stages={[\n    { label: \"Visits\", value: 12400 },\n    { label: \"Signups\", value: 4200 },\n    { label: \"Activated\", value: 1850 },\n    { label: \"Paid\", value: 480 },\n  ]}\n/>", render: e_charts_funnel_chart_example_0 },
    { label: "Share of the first stage", code: "<FunnelChart\n  share\n  stages={[\n    { label: \"Cart\", value: 8600 },\n    { label: \"Address\", value: 5200 },\n    { label: \"Payment\", value: 3900 },\n    { label: \"Placed\", value: 3400 },\n  ]}\n/>", render: e_charts_funnel_chart_example_1 },
    { label: "Compact, inspected", code: "<FunnelChart\ncompact\ndefaultSelected={1}\nstages={[\n  { label: \"Leads\", value: 900 },\n  { label: \"Qualified\", value: 340 },\n  { label: \"Closed\", value: 120 },\n]}\n/>", render: e_charts_funnel_chart_example_2 },
  ],
  donts: [
    { title: "FunnelChart", do: { caption: "Order the stages widest first and let the taper carry the drop-off.", code: "<FunnelChart\ntitle=\"Signup funnel\"\nstages={[\n  { label: \"Visits\", value: 12400 },\n  { label: \"Signups\", value: 4200 },\n  { label: \"Paid\", value: 480 },\n]}\n/>", render: e_charts_funnel_chart_dont_0_do }, dont: { caption: "A funnel that widens mid-way is not a funnel; a stage exceeding its predecessor warns and reads as an error.", code: "<FunnelChart\nstages={[\n  { label: \"Visits\", value: 4200 },\n  { label: \"Signups\", value: 12400 },\n]}\n/>", render: e_charts_funnel_chart_dont_0_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"FunnelChartProps","props":[{"name":"stages","type":"StackedSegment[]","required":true,"description":"Ordered stages, widest first."},{"name":"title","type":"string","required":false,"description":"Optional heading shown above the funnel."},{"name":"share","type":"boolean","required":false,"description":"Show each stage as a share of the FIRST stage instead of the conversion from the previous stage."},{"name":"compact","type":"boolean","required":false,"description":"Density (omit for the default funnel height)."},{"name":"formatValue","type":"(v: number) => string","required":false,"description":"Formats stage values (data formatting, not styling)."},{"name":"selected","type":"number | null","required":false,"description":"Press-to-inspect: the selected stage index (controlled). Pass null for none."},{"name":"defaultSelected","type":"number","required":false,"description":"Press-to-inspect: the initially selected stage (uncontrolled)."},{"name":"onSelect","type":"(index: number | null) => void","required":false,"description":"Fired when a press selects a stage (or clears it with null)."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
