/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { AppShell, Icon, Sidebar, Typography } = scope;
  return (
<AppShell>
  {({ open, setOpen }) => (
    <Sidebar
      responsive
      collapsible
      defaultActive="Dashboard"
      open={open}
      onOpenChange={setOpen}
      header={(collapsed) => (collapsed ? <Icon layoutGrid primary size={22} /> : <Typography body semibold>Acme</Typography>)}
      sections={[
        { items: [
          { label: "Dashboard", icon: "layoutGrid" },
          { label: "Inbox", icon: "inbox", badge: "3" }
        ] },
        { title: "Reports", icon: "barChart2", collapsible: true, items: [
          { label: "Analytics", icon: "barChart2" },
          { label: "Traffic", icon: "activity" }
        ] }
      ]}
    />
  )}
</AppShell>
  );
}
