/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/sidebar/sidebar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Sidebar } = scope;
  return (
<Sidebar
  bordered
  defaultActive="Dashboard"
  items={[
    { label: "Dashboard", icon: "layoutGrid" },
    { label: "Members", icon: "users" },
    { label: "Security", icon: "shield", badge: "3", badgeError: true }
  ]}
/>
  );
}
