/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/action-sheet/action-sheet.md
import type { ComponentDocs } from "../../../scope";
import e_organisms_action_sheet_example_0 from "./example-0";
import e_organisms_action_sheet_example_1 from "./example-1";
import e_organisms_action_sheet_example_2 from "./example-2";
import e_organisms_action_sheet_example_3 from "./example-3";
import e_organisms_action_sheet_example_4 from "./example-4";
import e_organisms_action_sheet_dont_0_do from "./dont-0-do";
import e_organisms_action_sheet_dont_0_dont from "./dont-0-dont";
import e_organisms_action_sheet_dont_1_do from "./dont-1-do";
import e_organisms_action_sheet_dont_1_dont from "./dont-1-dont";

export const docs: ComponentDocs = {
  dir: "action-sheet",
  category: "organisms",
  examples: [
    { label: "Default", code: "<ActionSheet\n  trigger=\"Add photo\"\n  actions={[\n    { label: \"Take Photo\", onPress: () => {} },\n    { label: \"Choose from Library\", onPress: () => {} }\n  ]}\n/>", render: e_organisms_action_sheet_example_0 },
    { label: "With a title and message", code: "<ActionSheet\n  trigger=\"Discard draft…\"\n  title=\"Discard draft?\"\n  message=\"Your unsaved changes will be lost.\"\n  actions={[\n    { label: \"Discard Changes\", onPress: () => {} },\n    { label: \"Keep Editing\", onPress: () => {} }\n  ]}\n/>", render: e_organisms_action_sheet_example_1 },
    { label: "Destructive action", code: "<ActionSheet\n  trigger=\"File options\"\n  actions={[\n    { label: \"Move to Folder\", onPress: () => {} },\n    { label: \"Delete File\", destructive: true, onPress: () => {} }\n  ]}\n/>", render: e_organisms_action_sheet_example_2 },
    { label: "Disabled action", code: "<ActionSheet\n  trigger=\"File options\"\n  actions={[\n    { label: \"Save\", onPress: () => {} },\n    { label: \"Save As…\", disabled: true, onPress: () => {} }\n  ]}\n/>", render: e_organisms_action_sheet_example_3 },
    { label: "Controlled", code: "<Stateful initial={false}>\n  {(open, setOpen) => (\n    <>\n      <Button onPress={() => setOpen(true)}>Share…</Button>\n      <ActionSheet\n        open={open}\n        onOpenChange={setOpen}\n        actions={[\n          { label: \"Copy Link\", onPress: () => {} },\n          { label: \"Send by Email\", onPress: () => {} }\n        ]}\n      />\n    </>\n  )}\n</Stateful>", render: e_organisms_action_sheet_example_4 },
  ],
  donts: [
    { title: "Right tool for the job", do: { caption: "Use an Action Sheet for a short list of choices triggered by a user action, with the dangerous option marked destructive.", code: "<ActionSheet\n  trigger=\"Add photo\"\n  title=\"Photo\"\n  actions={[\n    { label: \"Take Photo\", onPress: () => {} },\n    { label: \"Choose from Library\", onPress: () => {} },\n    { label: \"Remove Photo\", destructive: true, onPress: () => {} },\n  ]}\n/>", render: e_organisms_action_sheet_dont_0_do }, dont: { caption: "Use an Action Sheet for a single yes/no confirmation; an Alert Dialog is the focused tool for that.", code: "<ActionSheet\n  trigger=\"Confirm\"\n  title=\"Are you sure?\"\n  actions={[{ label: \"OK\", onPress: () => {} }]}\n/>", render: e_organisms_action_sheet_dont_0_dont } },
    { title: "Name the action, not a generic verb", do: { caption: "Label each row with the action it performs (Take Photo, Delete File, Move).", code: "<ActionSheet\n  trigger=\"File options\"\n  actions={[\n    { label: \"Delete File\", destructive: true, onPress: () => {} },\n    { label: \"Move to Folder\", onPress: () => {} },\n  ]}\n/>", render: e_organisms_action_sheet_dont_1_do }, dont: { caption: "Generic labels force the user to re-read the title to know what each row does.", code: "<ActionSheet\n  trigger=\"Delete file…\"\n  title=\"Delete file?\"\n  actions={[\n    { label: \"Yes\", destructive: true, onPress: () => {} },\n    { label: \"No\", onPress: () => {} },\n  ]}\n/>", render: e_organisms_action_sheet_dont_1_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"ActionSheetProps","props":[{"name":"open","type":"boolean","required":false,"description":"Controlled open state. Omit for uncontrolled (a `trigger` opens it)."},{"name":"onOpenChange","type":"(open: boolean) => void","required":false,"description":"Fired when the open state changes (trigger press, scrim tap, Cancel, an action, back/escape)."},{"name":"trigger","type":"string","required":false,"description":"Label for an optional trigger button. When set, the sheet renders the button and opens itself on press (uncontrolled). Omit when you drive `open` yourself."},{"name":"title","type":"string","required":false,"description":"Optional header title (a left-aligned primary-label heading on iOS, a short centered heading on web, left-aligned on Android)."},{"name":"message","type":"string","required":false,"description":"Optional header message under the title."},{"name":"actions","type":"ActionSheetAction[]","required":true,"description":"The action rows. Each runs its `onPress` then closes the sheet."},{"name":"cancelLabel","type":"string","required":false,"description":"The Cancel row label (default \"Cancel\")."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"StyleProp<ViewStyle>","required":false,"description":"Outer layout composition for the bottom-anchored stack, composed onto the stack container; not a restyle hook. (The device's bottom safe-area inset is applied automatically, so it clears the home indicator without a manual `paddingBottom`.)"}]}],
};
