/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/action-sheet/action-sheet.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { ActionSheet } = scope;
  return (
<ActionSheet
  trigger="Discard draft…"
  title="Discard draft?"
  message="Your unsaved changes will be lost."
  actions={[
    { label: "Discard Changes", onPress: () => {} },
    { label: "Keep Editing", onPress: () => {} }
  ]}
/>
  );
}
