/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/pie-chart/pie-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, PieChart } = scope;
  return (
<Card padded>
  <PieChart
    donut
    label="Traffic"
    slices={[
      { label: "Direct", value: 38 },
      { label: "Organic search", value: 24 },
      { label: "Social", value: 15 },
      { label: "Referral", value: 11 },
      { label: "Email", value: 8 },
      { label: "Paid", value: 4 }
    ]}
  />
</Card>
  );
}
