/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/pie-chart/pie-chart.md
import type { ComponentDocs } from "../../../scope";
import e_charts_pie_chart_example_0 from "./example-0";
import e_charts_pie_chart_example_1 from "./example-1";
import e_charts_pie_chart_dont_0_do from "./dont-0-do";
import e_charts_pie_chart_dont_0_dont from "./dont-0-dont";

export const docs: ComponentDocs = {
  dir: "pie-chart",
  category: "charts",
  examples: [
    { label: "Default", code: "<PieChart\n  label=\"Traffic\"\n  slices={[\n    { label: \"Direct\", value: 42 },\n    { label: \"Organic search\", value: 28 },\n    { label: \"Social\", value: 18 },\n    { label: \"Other\", value: 12 }\n  ]}\n/>", render: e_charts_pie_chart_example_0 },
    { label: "Donut", code: "<PieChart\n  donut\n  label=\"Traffic\"\n  slices={[\n    { label: \"Direct\", value: 42 },\n    { label: \"Organic search\", value: 28 },\n    { label: \"Social\", value: 18 },\n    { label: \"Other\", value: 12 }\n  ]}\n/>", render: e_charts_pie_chart_example_1 },
  ],
  donts: [
    { title: "Pie", do: { caption: "Keep slices to a handful and fold the tail into an \"Other\" slice; the legend carries exact shares.", code: "<Card padded>\n  <PieChart\n    label=\"Traffic\"\n    slices={[\n      { label: \"Direct\", value: 42 },\n      { label: \"Organic search\", value: 28 },\n      { label: \"Social\", value: 18 },\n      { label: \"Other\", value: 12 }\n    ]}\n  />\n</Card>\n", render: e_charts_pie_chart_dont_0_do }, dont: { caption: "A dozen sliver slices cycle the palette and become unreadable; nothing is comparable at a glance.", code: "<Card padded>\n  <PieChart\n    label=\"Traffic\"\n    slices={[\n      { label: \"Direct\", value: 22 },\n      { label: \"Organic\", value: 18 },\n      { label: \"Social\", value: 11 },\n      { label: \"Referral\", value: 9 },\n      { label: \"Email\", value: 8 },\n      { label: \"Paid\", value: 7 },\n      { label: \"Video\", value: 6 },\n      { label: \"Affiliates\", value: 6 },\n      { label: \"Push\", value: 5 },\n      { label: \"SMS\", value: 4 },\n      { label: \"Podcasts\", value: 2 },\n      { label: \"Misc\", value: 2 }\n    ]}\n  />\n</Card>\n", render: e_charts_pie_chart_dont_0_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"PieChartProps","props":[{"name":"slices","type":"StackedSegment[]","required":true,"description":"The slices, in order; each takes its share of the circle."},{"name":"label","type":"string","required":false,"description":"What the pie measures (e.g. \"Traffic sources\"); leads the accessible name."},{"name":"donut","type":"boolean","required":false,"description":"Draw an annular ring with the total and label centered inside."},{"name":"hideLegend","type":"boolean","required":false,"description":"Hide the legend (the labelled dots beside percentages)."},{"name":"compact","type":"boolean","required":false,"description":"Smaller diameter."},{"name":"selected","type":"number | null","required":false,"description":"Press-to-inspect: the selected slice index (controlled). Pass null for none."},{"name":"defaultSelected","type":"number","required":false,"description":"Press-to-inspect: the initially selected slice (uncontrolled)."},{"name":"onSelect","type":"(index: number | null) => void","required":false,"description":"Fired when a press selects a slice (or clears it with null)."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"For sizing/composition only."}]}],
};
