/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert-dialog/alert-dialog.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { AlertDialog } = scope;
  return (
<AlertDialog
  small
  title="Transfer ownership?"
  description="You will lose admin access to this workspace."
  confirmLabel="Transfer"
  trigger="Transfer ownership…"
/>
  );
}
