/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/navbars/navbars.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Card, Icon, Kbd, Typography, Row, Container } = scope;
  return (
<Card flat flush style={{ overflow: "hidden" }}>
  <Row alignCenter snug pad style={{ height: 56 }}>
    <Typography small semibold>Canvas</Typography>
    <Container sm start>
      <Button outline block iconLeft={<Icon search muted size={13} />} iconRight={<Kbd>⌘K</Kbd>}>Search…</Button>
    </Container>
  </Row>
</Card>
  );
}
