/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/navbars/navbars.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Navbar } = scope;
  return (
<Navbar floating brand="Canvas" links={["Dashboard", "Users", "Settings"]} />
  );
}
