/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Alert } = scope;
  return (
<Alert
  success
  icon="✓"
  title="All set"
  description="Your changes have been saved successfully."
/>
  );
}
