/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Alert, Column, Container } = scope;
  return (
<Column snug>
  <Container xs start>
    <Alert title="In an xs Container" description="The banner fills the 320px step, the measure of a short form." />
  </Container>
  <Alert title="Bare" description="No container of its own: the banner fills whatever parent it sits in." />
</Column>
  );
}
