/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/alert/alert.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Alert } = scope;
  return (
<Alert
  destructive
  icon="✕"
  title="Something went wrong"
  description="Could not save your changes. Please try again."
/>
  );
}
