/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/pagination/pagination.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Pagination, Column } = scope;
  return (
<Column relaxed>
  <Pagination small defaultPage={2} total={12} />
  <Pagination defaultPage={2} total={12} />
  <Pagination large defaultPage={2} total={12} />
</Column>
  );
}
