/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/pagination/pagination.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Pagination } = scope;
  return (
<Pagination defaultPage={2} total={12} withSize defaultPageSize={10} pageSizes={[10, 25, 50]} />
  );
}
