/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/bar-list/bar-list.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { BarList } = scope;
  return (
<BarList
title="Top pages"
items={[
  { label: "/pricing", value: 18400, delta: "+12%" },
  { label: "/docs", value: 12100, delta: "-4%", down: true },
]}
/>
  );
}
