/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/bar-list/bar-list.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, BarList } = scope;
  return (
<Container md>
  <BarList
  title="Sign-up sources"
  share
  items={[
    { label: "google", value: 412 },
    { label: "email", value: 318 },
    { label: "github", value: 142 },
    { label: "passkey", value: 88 },
  ]}
/>
</Container>
  );
}
