/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/bar-list/bar-list.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, BarList } = scope;
  return (
<Card>
  <BarList
    plain
    items={[
      { label: "Deploys", value: 42 },
      { label: "Rollbacks", value: 3 },
      { label: "Incidents", value: 1 },
    ]}
  />
</Card>
  );
}
