/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/bar-list/bar-list.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography, Column, Container, BarList } = scope;
  return (
<Container md>
  <Card padded>
    <Column>
      <Typography h4>This week</Typography>
      <BarList
        plain
        compact
        items={[
          { label: "Deploys", value: 42 },
          { label: "Rollbacks", value: 3, chart4: true },
          { label: "Incidents", value: 1, chart8: true },
        ]}
      />
    </Column>
  </Card>
</Container>
  );
}
