/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stats/stats.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stats } = scope;
  return (
<Stats
  plain
  items={[
    { label: "Revenue", value: "$48.2k" },
    { label: "Orders", value: "842" },
    { label: "Conversion", value: "3.6%" }
  ]}
/>
  );
}
