/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stats/stats.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stats } = scope;
  return (
<Stats
  items={[
    { label: "Total users", value: "12,847", delta: "+12.5%" },
    { label: "Error rate", value: "0.12%", delta: "+0.03%", down: true },
    { label: "Avg. session", value: "4m 32s", delta: "last 30 days", steady: true }
  ]}
/>
  );
}
