/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stats/stats.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stats } = scope;
  return (
<Stats
  onPressItem={() => {}}
  items={[
    { label: "Active users", value: "71,897" },
    { label: "Revenue", value: "$48.2k" }
  ]}
/>
  );
}
