/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/media-objects/media-objects.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, MediaObject, Container } = scope;
  return (
<Container xs>
  <MediaObject bordered center src="/ada-lovelace.jpg" title="Ada Lovelace" description="ada.lovelace@analytical-engine.example.com" action={<Button outline small>Invite</Button>} />
</Container>
  );
}
