/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/media-objects/media-objects.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { MediaObject, Column, Container } = scope;
  return (
<Container xs>
  <Column cozy>
    <MediaObject avatar="RC" title="Rachel Chen" description="rachel.chen@example.com" />
    <MediaObject compact avatar="RC" title="Rachel Chen" description="rachel.chen@example.com" />
  </Column>
</Container>
  );
}
