/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/media-objects/media-objects.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, MediaObject } = scope;
  return (
<MediaObject bordered src="/ada-lovelace.jpg" title="Ada Lovelace" description="ada@example.com" action={<Button outline small>Invite</Button>} />
  );
}
