/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/sparkline/sparkline.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Column, Container, Sparkline } = scope;
  return (
<Container xxxs>
  <Column>
    <Sparkline compact values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} />
    <Sparkline values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} />
    <Sparkline tall values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} />
  </Column>
</Container>
  );
}
