/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/sparkline/sparkline.md
import type { ComponentDocs } from "../../../scope";
import e_charts_sparkline_example_0 from "./example-0";
import e_charts_sparkline_example_1 from "./example-1";
import e_charts_sparkline_example_2 from "./example-2";
import e_charts_sparkline_example_3 from "./example-3";
import e_charts_sparkline_example_4 from "./example-4";
import e_charts_sparkline_dont_0_do from "./dont-0-do";
import e_charts_sparkline_dont_0_dont from "./dont-0-dont";

export const docs: ComponentDocs = {
  dir: "sparkline",
  category: "charts",
  examples: [
    { label: "Default", code: "<Container xxxs>\n  <Sparkline values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} />\n</Container>", render: e_charts_sparkline_example_0 },
    { label: "Tones", code: "<Container xxxs>\n  <Column>\n    <Sparkline primary values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} />\n    <Sparkline success values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} />\n    <Sparkline destructive values={[24, 20, 16, 18, 14, 16, 10, 12, 6, 8, 4]} />\n    <Sparkline muted values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} />\n  </Column>\n</Container>", render: e_charts_sparkline_example_1 },
    { label: "Sizes", code: "<Container xxxs>\n  <Column>\n    <Sparkline compact values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} />\n    <Sparkline values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} />\n    <Sparkline tall values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} />\n  </Column>\n</Container>", render: e_charts_sparkline_example_2 },
    { label: "Line", code: "<Container xxxs>\n  <Sparkline line values={[4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24]} />\n</Container>", render: e_charts_sparkline_example_3 },
    { label: "Track", code: "<Container xxxs>\n  <Sparkline track values={[0, 0, 0, 0, 0, 0, 0, 0]} />\n</Container>", render: e_charts_sparkline_example_4 },
  ],
  donts: [
    { title: "Pair with a value", do: { caption: "Anchor the sparkline to an explicit headline value and delta with the Stats molecule, which owns the metric-card anatomy and renders the trend strip from its `spark` field.", code: "<Container xxxs>\n  <Stats items={[{ label: \"Requests\", value: \"24.5k\", delta: \"+8.2%\", spark: [4, 8, 6, 12, 10, 16, 14, 18, 16, 20, 24] }]} />\n</Container>", render: e_charts_sparkline_dont_0_do }, dont: { caption: "Draw a bare trend strip with no current value; the reader has to decode the slope.", code: "<View style={{ flexDirection: \"row\", alignItems: \"flex-end\", gap: 2, height: 24 }}>\n  <View style={{ flexGrow: 1, borderRadius: 2, backgroundColor: \"#4f46e5\", height: 8 }} />\n  <View style={{ flexGrow: 1, borderRadius: 2, backgroundColor: \"#4f46e5\", height: 16 }} />\n  <View style={{ flexGrow: 1, borderRadius: 2, backgroundColor: \"#4f46e5\", height: 24 }} />\n</View>", render: e_charts_sparkline_dont_0_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"SparklineProps","props":[{"name":"values","type":"number[]","required":true,"description":"The series to plot; each value becomes one bar, sized against the max."},{"name":"primary","type":"boolean","required":false,"description":"Tone (pick one; default `primary`). Colors the marks."},{"name":"success","type":"boolean","required":false,"description":"Tone (pick one; default `primary`). Colors the marks."},{"name":"destructive","type":"boolean","required":false,"description":"Tone (pick one; default `primary`). Colors the marks."},{"name":"muted","type":"boolean","required":false,"description":"Tone (pick one; default `primary`). Colors the marks."},{"name":"compact","type":"boolean","required":false,"description":"Height (pick one; default medium)."},{"name":"tall","type":"boolean","required":false,"description":"Height (pick one; default medium)."},{"name":"line","type":"boolean","required":false,"description":"A continuous 2px trend line with an area wash and end marker, instead of the bar strip."},{"name":"track","type":"boolean","required":false,"description":"Paint the plot area with the muted track, giving the strip a visible frame. Two things it buys: a flat or all-zero series reads as a chart sitting at zero rather than as one that failed to load, and a row of strips scans evenly because every one of them holds the same band whatever its data. Use it wherever strips sit side by side (a Stats row); a lone sparkline inside running text is usually better without."},{"name":"accessibilityLabel","type":"string","required":false,"description":"Accessible summary (e.g. \"requests, last 11 days\")."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"For sizing/composition only (e.g. maxWidth); not a styling escape hatch."}]}],
};
