/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/text-input/text-input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { TextInput } = scope;
  return (
<TextInput accessibilityLabel="Notes" multiline defaultValue={"Multi-line text\nwraps and grows as you type."} />
  );
}
