/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/text-input/text-input.md
import type { ComponentDocs } from "../../../scope";
import e_atoms_text_input_example_0 from "./example-0";
import e_atoms_text_input_example_1 from "./example-1";
import e_atoms_text_input_example_2 from "./example-2";

export const docs: ComponentDocs = {
  dir: "text-input",
  category: "atoms",
  examples: [
    { label: "Default", code: "<TextInput accessibilityLabel=\"Your name\" defaultValue=\"Ada Lovelace\" />", render: e_atoms_text_input_example_0 },
    { label: "Placeholder", code: "<TextInput placeholder=\"Search components...\" />", render: e_atoms_text_input_example_1 },
    { label: "Multiline", code: "<TextInput accessibilityLabel=\"Notes\" multiline defaultValue={\"Multi-line text\\nwraps and grows as you type.\"} />", render: e_atoms_text_input_example_2 },
  ],
  donts: [

  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [],
};
