/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Text, Input, Column } = scope;
  return (
<Column tight>
  <Text style={{ fontSize: 14, fontWeight: "500" }}>Email</Text>
  <Input placeholder="you@example.com" />
</Column>
  );
}
