/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Text, Input, Column } = scope;
  return (
<Column tight>
  <Input label="Email" required value="rachel.chen" />
  <Text style={{ fontSize: 12, color: "#e7000b" }}>Enter a valid email address.</Text>
</Column>
  );
}
