/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Field, Input, Select, Textarea, Column } = scope;
  return (
<Column snug>
  <Field label="Full name" required>
    <Input placeholder="Rachel Chen" />
  </Field>
  <Field label="Role" helper="Controls what this person can see.">
    <Select options={["Admin", "Editor", "Viewer"]} placeholder="Pick a role" />
  </Field>
  <Field label="Notes">
    <Textarea rows={3} placeholder="Anything worth remembering" />
  </Field>
</Column>
  );
}
