/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/field/field.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Field, Input } = scope;
  return (
<Field label="Workspace URL" helper="Lowercase letters, numbers and hyphens.">
  <Input placeholder="acme-inc" />
</Field>
  );
}
