/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/slider/slider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Slider, Column, Container } = scope;
  return (
<Column>
  <Slider xs start defaultValue={40}>xs step, pinned to the start (320)</Slider>
  <Slider lg start defaultValue={40}>lg step, pinned to the start (512)</Slider>
  <Container lg start><Slider defaultValue={40}>Bare, in an lg Container: fills it (512)</Slider></Container>
</Column>
  );
}
