/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Form, Input } = scope;
  return (
<Form twoColumn submitLabel="Save" style={{ width: 560, maxWidth: "100%" }}>
  <Input label="Street address" placeholder="123 Market St" />
  <Input label="ZIP" placeholder="94103" />
</Form>
  );
}
