/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Form, Input } = scope;
  return (
<Form submitLabel="Sign in">
  <Input label="Email" placeholder="you@example.com" />
  <Input label="Password" />
</Form>
  );
}
