/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Checkbox, Form, FormSection, Input, Container } = scope;
  return (
<Container xl>
  <Form submitLabel="Save">
    <FormSection title="Personal info" description="This information will be displayed on your public profile.">
      <Input label="Full name" defaultValue="Rachel Chen" />
      <Input label="Email" defaultValue="rachel@example.com" />
    </FormSection>
    <FormSection title="Notifications" description="Choose how you'd like to be notified.">
      <Checkbox defaultChecked>Email notifications</Checkbox>
      <Checkbox>SMS alerts</Checkbox>
    </FormSection>
  </Form>
</Container>
  );
}
