/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Form, Input, Select, Row } = scope;
  return (
<Form submitLabel="Save address">
  <Input label="Street address" placeholder="123 Main Street" autoComplete="street-address" textContentType="streetAddressLine1" />
  <Input label="Apartment, suite, unit (optional)" placeholder="Apt 5B" textContentType="streetAddressLine2" />
  <Row relaxed>
    <Input label="City" placeholder="San Francisco" textContentType="addressCity" />
    <Input label="ZIP code" placeholder="94105" keyboardType="number-pad" autoComplete="postal-code" textContentType="postalCode" />
  </Row>
  <Select
    label="Country"
    defaultValue="US"
    options={[
      { value: "US", label: "United States", leading: "🇺🇸" },
      { value: "CA", label: "Canada", leading: "🇨🇦" },
      { value: "GB", label: "United Kingdom", leading: "🇬🇧" },
      { value: "DE", label: "Germany", leading: "🇩🇪" },
      { value: "JP", label: "Japan", leading: "🇯🇵" },
    ]}
  />
</Form>
  );
}
