/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Form, Select, Switch } = scope;
  return (
<Form twoColumn submitLabel="Save" cancelLabel="Cancel">
  <Select label="Role" options={["Admin", "Editor", "Viewer"]} defaultValue="Editor" />
  <Switch defaultChecked description="Email me when someone mentions me.">Notifications</Switch>
</Form>
  );
}
