/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Form, Input } = scope;
  return (
<Form twoColumn submitLabel="Create" cancelLabel="Cancel" style={{ width: 560, maxWidth: "100%" }}>
  <Input label="First name" placeholder="Ada" />
  <Input label="Last name" placeholder="King" />
  <Input label="Email" placeholder="ada@example.com" />
</Form>
  );
}
