/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Field, Form, Input, Select, Row } = scope;
  return (
<Form submitLabel="Save address">
  <Field label="Street address" error="Street address is required.">
    <Input placeholder="123 Main Street" />
  </Field>
  <Field label="Apartment, suite, unit (optional)" error="Street address is required.">
    <Input placeholder="Apt 5B" />
  </Field>
  <Row relaxed alignStart>
    <Field label="City" error="City is required.">
      <Input placeholder="San Francisco" />
    </Field>
    <Field label="ZIP code" error="Invalid postal code.">
      <Input defaultValue="101" keyboardType="number-pad" />
    </Field>
  </Row>
  <Select
    label="Country"
    defaultValue="US"
    options={[
      { value: "US", label: "United States", leading: "🇺🇸" },
      { value: "CA", label: "Canada", leading: "🇨🇦" },
      { value: "GB", label: "United Kingdom", leading: "🇬🇧" },
    ]}
  />
</Form>
  );
}
