/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/form/form.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, Form, Input, Typography, Column, Container } = scope;
  return (
<Stateful initial={0}>
  {(saves, setSaves) => (
    <Column snug>
      <Container sm>
        <Form submitLabel="Sign in" onSubmit={() => setSaves(saves + 1)}>
          <Input label="Email" placeholder="you@example.com" />
          <Input label="Password" />
        </Form>
      </Container>
      <Typography muted>{saves === 0 ? "Not submitted yet" : `Submitted ${saves} ${saves === 1 ? "time" : "times"}`}</Typography>
    </Column>
  )}
</Stateful>
  );
}
