/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/waterfall-chart/waterfall-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, WaterfallChart } = scope;
  return (
<Container xl>
  <WaterfallChart
  title="Q3 revenue bridge"
  steps={[
    { label: "Q2", value: 4200, total: true },
    { label: "New", value: 980 },
    { label: "Churn", value: -540 },
    { label: "Q3", total: true },
  ]}
/>
</Container>
  );
}
