/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/action-panels/action-panels.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { ActionPanel } = scope;
  return (
<ActionPanel title="Two-factor authentication" description="Add an extra layer of security to your account by requiring a verification code on login." toggle defaultChecked />
  );
}
