/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/action-panels/action-panels.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { ActionPanel } = scope;
  return (
<ActionPanel
  title="Weekly digest"
  description="A summary of workspace activity, sent every Monday."
  actionLabel="Subscribe"
  inline
/>
  );
}
