/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/scatter-plot/scatter-plot.md
import type { ComponentDocs } from "../../../scope";
import e_charts_scatter_plot_example_0 from "./example-0";
import e_charts_scatter_plot_example_1 from "./example-1";

export const docs: ComponentDocs = {
  dir: "scatter-plot",
  category: "charts",
  examples: [
    { label: "Default", code: "<ScatterPlot\n  title=\"Load vs latency\"\n  series={[\n    { label: \"us-east\", points: [{ x: 94, y: 20 }, { x: 220, y: 37 }, { x: 339, y: 63 }, { x: 446, y: 71 }, { x: 596, y: 99 }, { x: 741, y: 115 }] },\n    { label: \"eu-west\", points: [{ x: 114, y: 33 }, { x: 227, y: 52 }, { x: 340, y: 92 }, { x: 455, y: 111 }, { x: 579, y: 129 }, { x: 737, y: 141 }] },\n    { label: \"ap-south\", points: [{ x: 133, y: 45 }, { x: 251, y: 72 }, { x: 377, y: 102 }, { x: 492, y: 135 }, { x: 613, y: 161 }, { x: 740, y: 171 }] }\n  ]}\n/>", render: e_charts_scatter_plot_example_0 },
    { label: "Compact single series", code: "<ScatterPlot\n  compact\n  series={[\n    { label: \"Campaigns\", points: [{ x: 1.2, y: 14 }, { x: 2.8, y: 26 }, { x: 4.2, y: 38 }, { x: 5.9, y: 46 }, { x: 7.3, y: 58 }, { x: 8.1, y: 63 }] }\n  ]}\n/>", render: e_charts_scatter_plot_example_1 },
  ],
  donts: [

  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"ScatterPlotProps","props":[{"name":"series","type":"ScatterSeries[]","required":true,"description":"The point clouds; colors follow the chart-1..8 tokens in fixed order."},{"name":"title","type":"string","required":false,"description":"Optional heading shown above the plot."},{"name":"success","type":"boolean","required":false,"description":"Tone (single-series only; pick one; default is the primary fill)."},{"name":"destructive","type":"boolean","required":false,"description":"Tone (single-series only; pick one; default is the primary fill)."},{"name":"compact","type":"boolean","required":false,"description":"Density (omit for the default plot size)."},{"name":"hideLegend","type":"boolean","required":false,"description":"Furniture visibility."},{"name":"hideGrid","type":"boolean","required":false,"description":"Furniture visibility."},{"name":"hideAxes","type":"boolean","required":false,"description":"Furniture visibility."},{"name":"formatValue","type":"(v: number) => string","required":false,"description":"Formats tick labels and accessible values (data formatting, not styling)."},{"name":"selected","type":"ScatterSelection | null","required":false,"description":"Press-to-inspect: the selected point (controlled). Pass null for none."},{"name":"defaultSelected","type":"ScatterSelection","required":false,"description":"Press-to-inspect: the initially selected point (uncontrolled)."},{"name":"onSelect","type":"(selection: ScatterSelection | null) => void","required":false,"description":"Fired when a press selects a point (or clears it with null)."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
