/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/line-chart/line-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, LineChart } = scope;
  return (
<Container xl>
  <LineChart
  title="Signups"
  labels={["Jan", "Feb", "Mar", "Apr", "May", "Jun"]}
  series={[
    { label: "Web", values: [120, 180, 150, 240, 300, 280] },
    { label: "Mobile", values: [60, 90, 140, 160, 220, 260] }
  ]}
  curved
/>
</Container>
  );
}
