/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/line-chart/line-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { LineChart } = scope;
  return (
<LineChart
title="OLY · today"
labels={["9:30a", "9:40a", "9:50a", "10:00a", "10:10a", "10:20a", "10:30a", "10:40a", "10:50a", "11:00a", "11:10a", "11:20a", "11:30a", "11:40a", "11:50a", "12:00p", "12:10p", "12:20p", "12:30p", "12:40p", "12:50p", "1:00p", "1:10p", "1:20p", "1:30p", "1:40p", "1:50p", "2:00p", "2:10p", "2:20p", "2:30p", "2:40p", "2:50p", "3:00p", "3:10p", "3:20p", "3:30p", "3:40p", "3:50p"]}
series={[{ label: "Price", values: [186.1, 186.6, 186.4, 187.1, 187.5, 187.5, 187.6, 187.3, 186.8, 187.5, 187.0, 186.6, 186.7, 187.1, 186.7, 187.4, 187.5, 187.4, 188.1, 187.6, 188.5, 188.4, 188.9, 189.2, 189.5, 189.6, 190.5, 190.6, 190.7, 190.4, 190.2, 190.8, 190.5, 190.5, 191.4, 191.1, 191.8, 191.6, 191.7] }]}
baseline={188}
fade
curved
/>
  );
}
