/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/line-chart/line-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { LineChart } = scope;
  return (
<LineChart
  title="Active users"
  labels={["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"]}
  series={[
    { label: "Web", values: [119, 122, 131, 147, 157, 176, 182] },
    { label: "Mobile", values: [63, 93, 101, 121, 162, 207, 251] }
  ]}
/>
  );
}
