/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/line-chart/line-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { LineChart } = scope;
  return (
<LineChart
  compact
  title="Signups"
  labels={["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]}
  series={[{ label: "Signups", values: [24, 31, 28, 42, 39, 47, 51] }]}
/>
  );
}
