/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/line-chart/line-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, LineChart } = scope;
  return (
<Container xl>
  <LineChart
  title="Sessions by platform"
  labels={["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]}
  series={[
    { label: "Web", values: [42, 48, 45, 61, 58, 71, 84] },
    { label: "iOS", values: [28, 31, 36, 34, 41, 49, 56] },
    { label: "Android", values: [19, 22, 21, 27, 30, 33, 41] }
  ]}
  fade
  curved
/>
</Container>
  );
}
