/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/card/card.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { shadow, Card, Typography, Column, Container } = scope;
  return (
<Container sm>
  <Card flat>
    <Column tight>
      <Typography lead semibold>Outlined and quiet</Typography>
      <Typography small muted>Flat drops the shadow so the card sits flush with the page. On Android this is the Material outlined card.</Typography>
    </Column>
  </Card>
</Container>
  );
}
