/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/card/card.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Card, CardContent, CardMedia, Typography, Row, Column } = scope;
  return (
<Card flush>
  <CardMedia src="/kira-tanaka.jpg" height={180} alt="Portrait of Kira Tanaka" />
  <CardContent>
    <Column cozy>
      <Column tight>
        <Typography h5 semibold>Kira Tanaka</Typography>
        <Typography small muted>Design engineer. Ships the pixels and the pipeline that delivers them.</Typography>
      </Column>
      <Row snug>
        <Button primary small>Follow</Button>
        <Button outline small>Message</Button>
      </Row>
    </Column>
  </CardContent>
</Card>
  );
}
