/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/card/card.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography } = scope;
  return (
<Card raised>
  <Typography lead semibold>Lifted above the page</Typography>
</Card>
  );
}
