/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/card/card.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Icon, Container } = scope;
  return (
<Container sm>
  <Card
  title="Identity"
  icon={<Icon user muted size={16} />}
  description="Core attributes"
  body="Name, primary email, and sign-in methods for this account."
  footer="Updated 2 minutes ago"
/>
</Container>
  );
}
