/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/card/card.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Button, Card, MediaObject } = scope;
  return (
<Card>
  <MediaObject
    src="/rachel-chen.jpg"
    title="Rachel Chen"
    description="Platform engineering, San Francisco"
    action={<Button outline small>View</Button>}
    center
  />
</Card>
  );
}
