/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/row-menu/row-menu.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { RowMenu } = scope;
  return (
<RowMenu links items={[{ label: "Profile" }, { label: "Billing" }, { label: "Members" }]} />
  );
}
