/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/row-menu/row-menu.md
import type { ComponentDocs } from "../../../scope";
import e_organisms_row_menu_example_0 from "./example-0";
import e_organisms_row_menu_example_1 from "./example-1";
import e_organisms_row_menu_example_2 from "./example-2";
import e_organisms_row_menu_example_3 from "./example-3";
import e_organisms_row_menu_example_4 from "./example-4";
import e_organisms_row_menu_dont_0_do from "./dont-0-do";
import e_organisms_row_menu_dont_0_dont from "./dont-0-dont";
import e_organisms_row_menu_dont_1_do from "./dont-1-do";
import e_organisms_row_menu_dont_1_dont from "./dont-1-dont";
import e_organisms_row_menu_dont_2_do from "./dont-2-do";
import e_organisms_row_menu_dont_2_dont from "./dont-2-dont";

export const docs: ComponentDocs = {
  dir: "row-menu",
  category: "organisms",
  examples: [
    { label: "Default", code: "<RowMenu\n  items={[\n    { label: \"Edit\" },\n    { label: \"Duplicate\" },\n    { label: \"Delete\", destructive: true, separatorBefore: true }\n  ]}\n/>", render: e_organisms_row_menu_example_0 },
    { label: "Links", code: "<RowMenu links items={[{ label: \"Profile\" }, { label: \"Billing\" }, { label: \"Members\" }]} />", render: e_organisms_row_menu_example_1 },
    { label: "Section label", code: "<RowMenu sectionLabel=\"Actions\" items={[{ label: \"Edit\" }, { label: \"Duplicate\" }, { label: \"Rename\" }]} />", render: e_organisms_row_menu_example_2 },
    { label: "Leading icons", code: "<RowMenu\n  items={[\n    { label: \"Edit\", icon: \"pencil\" },\n    { label: \"Duplicate\", icon: \"copy\" },\n    { label: \"Settings\", icon: \"settings\" }\n  ]}\n/>", render: e_organisms_row_menu_example_3 },
    { label: "Disabled item", code: "<RowMenu items={[{ label: \"Edit\" }, { label: \"Duplicate\" }, { label: \"Clear column\", disabled: true }]} />", render: e_organisms_row_menu_example_4 },
  ],
  donts: [
    { title: "When to use", do: { caption: "Collapse per-row actions behind a ··· trigger; keep Delete separated and danger-colored.", code: "<RowMenu open sectionLabel=\"Actions\" items={[\n    { label: \"Edit\", icon: \"pencil\" },\n    { label: \"Duplicate\", icon: \"copy\" },\n    { label: \"Delete\", icon: \"trash\", destructive: true, separatorBefore: true }\n  ]} />", render: e_organisms_row_menu_dont_0_do }, dont: { caption: "Splaying every row action inline multiplies visual noise across every table row.", code: "<View style={{ flexDirection: \"row\", flexWrap: \"wrap\", gap: 8 }}>\n  <Button ghost small>Edit</Button>\n  <Button ghost small>Duplicate</Button>\n  <Button destructive small>Delete</Button>\n</View>", render: e_organisms_row_menu_dont_0_dont } },
    { title: "Actions", do: { caption: "Click an item: place destructive actions last, color them, and split them off with a divider.", code: "<RowMenu open items={[\n    { label: \"Edit\" },\n    { label: \"Duplicate\" },\n    { label: \"Delete\", destructive: true, separatorBefore: true }\n  ]} />", render: e_organisms_row_menu_dont_1_do }, dont: { caption: "Click an item: a destructive action sandwiched between routine ones invites a costly misclick.", code: "<RowMenu open items={[\n    { label: \"Edit\" },\n    { label: \"Delete\", destructive: true },\n    { label: \"Duplicate\" }\n  ]} />", render: e_organisms_row_menu_dont_1_dont } },
    { title: "Links", do: { caption: "Pass `links` so rows render as real navigation links, and mark the current page with an active highlight.", code: "<RowMenu open links items={[\n    { label: \"Profile\" },\n    { label: \"Billing\" },\n    { label: \"Members\" }\n  ]} />", render: e_organisms_row_menu_dont_2_do }, dont: { caption: "Buttons can't be opened in a new tab, bookmarked, or middle-clicked, navigation needs real links.", code: "<RowMenu open items={[\n    { label: \"Profile\" },\n    { label: \"Billing\" },\n    { label: \"Members\" }\n  ]} />", render: e_organisms_row_menu_dont_2_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"RowMenuProps","props":[{"name":"items","type":"RowMenuItem[]","required":true,"description":"The menu rows, top to bottom."},{"name":"open","type":"boolean","required":false,"description":"Controlled open state. Omit for uncontrolled (the trigger toggles it)."},{"name":"onOpenChange","type":"(open: boolean) => void","required":false,"description":"Fired when the open state changes."},{"name":"links","type":"boolean","required":false,"description":"Render rows as navigation links rather than action buttons."},{"name":"sectionLabel","type":"string","required":false,"description":"Show a muted section label heading the menu."},{"name":"onSelect","type":"(item: RowMenuItem, index: number) => void","required":false,"description":"Fired with the selected item and its index when a row is pressed."},{"name":"triggerLabel","type":"string","required":false,"description":"Accessible name for the icon-only ⋯ trigger. Defaults to \"More options\"."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
