/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/container/container.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography, Container } = scope;
  return (
<Container sm>
  <Card padded>
    <Typography medium>Sign in</Typography>
    <Typography small muted>The card fills the container; the container caps at the sm step (384).</Typography>
  </Card>
</Container>
  );
}
