/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/container/container.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography, Container } = scope;
  return (
<Container sm start>
  <Card padded>
    <Typography small>A leading-edge measure for a settings row.</Typography>
  </Card>
</Container>
  );
}
