/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/icon/icon.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { IconGallery } = scope;
  return (
<IconGallery />
  );
}
