/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/icon/icon.md
import type { ComponentDocs } from "../../../scope";
import e_atoms_icon_example_0 from "./example-0";
import e_atoms_icon_example_1 from "./example-1";
import e_atoms_icon_example_2 from "./example-2";
import e_atoms_icon_example_3 from "./example-3";
import e_atoms_icon_example_4 from "./example-4";
import e_atoms_icon_example_5 from "./example-5";
import e_atoms_icon_example_6 from "./example-6";
import e_atoms_icon_dont_0_do from "./dont-0-do";
import e_atoms_icon_dont_0_dont from "./dont-0-dont";
import e_atoms_icon_dont_1_do from "./dont-1-do";
import e_atoms_icon_dont_1_dont from "./dont-1-dont";
import e_atoms_icon_dont_2_do from "./dont-2-do";
import e_atoms_icon_dont_2_dont from "./dont-2-dont";
import e_atoms_icon_dont_3_do from "./dont-3-do";
import e_atoms_icon_dont_3_dont from "./dont-3-dont";
import e_atoms_icon_dont_4_do from "./dont-4-do";
import e_atoms_icon_dont_4_dont from "./dont-4-dont";

export const docs: ComponentDocs = {
  dir: "icon",
  category: "atoms",
  examples: [
    { label: "Default", code: "<Icon shield />", render: e_atoms_icon_example_0 },
    { label: "Primary", code: "<Icon shield primary />", render: e_atoms_icon_example_1 },
    { label: "Destructive", code: "<Icon shield destructive />", render: e_atoms_icon_example_2 },
    { label: "Success", code: "<Icon circleCheck success />", render: e_atoms_icon_example_3 },
    { label: "Warning", code: "<Icon alertTriangle warning />", render: e_atoms_icon_example_4 },
    { label: "Muted", code: "<Icon shield muted />", render: e_atoms_icon_example_5 },
    { label: "Gallery", code: "<IconGallery />", render: e_atoms_icon_example_6 },
  ],
  donts: [
    { title: "Stroke coherence", do: { caption: "One outline style at 1.75 stroke across the whole set.", code: "<Row alignCenter relaxed>\n  <Icon home size={28} />\n  <Icon search size={28} />\n  <Icon bell size={28} />\n</Row>", render: e_atoms_icon_dont_0_do }, dont: { caption: "Mixed stroke weights and a stray filled glyph make a set look incoherent.", code: "<View style={{ flexDirection: \"row\", alignItems: \"center\", gap: 20 }}>\n  <Icon home muted size={20} />\n  <Icon search destructive size={34} />\n  <Icon bell primary size={28} />\n</View>", render: e_atoms_icon_dont_0_dont } },
    { title: "foreground", do: { caption: "Leave the stroke at its default: it paints the theme foreground and follows light and dark on its own, no color prop needed.", code: "<Icon mail size={28} />", render: e_atoms_icon_dont_1_do }, dont: { caption: "Hard-coding a hex stroke pins the icon to one theme; it stays black on a dark surface and disappears.", code: "<View style={{ flexDirection: \"row\", alignItems: \"center\", justifyContent: \"center\", borderRadius: 6, backgroundColor: tokens.foreground, padding: 12 }}>\n  <Icon mail size={28} />\n</View>", render: e_atoms_icon_dont_1_dont } },
    { title: "primary", do: { caption: "Reserve text-primary for the one active or selected icon; keep the rest muted.", code: "<Row alignCenter relaxed>\n  <Icon home muted size={22} />\n  <Icon star primary size={22} />\n  <Icon settings muted size={22} />\n</Row>", render: e_atoms_icon_dont_2_do }, dont: { caption: "Painting a whole toolbar primary spends the accent on everything, so nothing reads as emphasized.", code: "<View style={{ flexDirection: \"row\", alignItems: \"center\", gap: 20 }}>\n  <Icon home primary size={22} />\n  <Icon search primary size={22} />\n  <Icon settings primary size={22} />\n</View>", render: e_atoms_icon_dont_2_dont } },
    { title: "destructive", do: { caption: "Keep text-destructive for genuinely destructive actions like delete, so red always means consequence.", code: "<Icon trash destructive size={28} />", render: e_atoms_icon_dont_3_do }, dont: { caption: "A red download icon implies danger on a perfectly safe action and trains users to ignore the warning color.", code: "<Icon download destructive size={28} />", render: e_atoms_icon_dont_3_dont } },
    { title: "muted", do: { caption: "Use the muted tone for secondary, inline hint icons where its color matches the helper text.", code: "<Row alignCenter snug>\n  <Icon info muted size={16} />\n  <Typography small muted>Optional, used only for recovery</Typography>\n</Row>", render: e_atoms_icon_dont_4_do }, dont: { caption: "A muted icon inside a solid primary button reads as disabled and clashes with the high-contrast label.", code: "<Pressable style={{ flexDirection: \"row\", alignItems: \"center\", justifyContent: \"center\", gap: 8, borderRadius: 6, backgroundColor: tokens.primary, paddingHorizontal: 16, paddingVertical: 8 }}>\n  <Icon plus muted size={16} />\n  <Text style={{ fontSize: 14, lineHeight: 20, fontWeight: \"500\", color: tokens[\"primary-foreground\"] }}>New project</Text>\n</Pressable>", render: e_atoms_icon_dont_4_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"IconProps","props":[{"name":"primary","type":"boolean","required":false,"description":"Color axis: pass one (default foreground). First match wins."},{"name":"primaryForeground","type":"boolean","required":false,"description":"Contrast color for a glyph on a primary surface (e.g. a primary button)."},{"name":"destructive","type":"boolean","required":false,"description":""},{"name":"success","type":"boolean","required":false,"description":"Positive/green status (matches Alert's success tone, scheme-aware)."},{"name":"warning","type":"boolean","required":false,"description":"Caution/amber status (the warning token, scheme-aware; matches Alert/Toast warning)."},{"name":"muted","type":"boolean","required":false,"description":""},{"name":"size","type":"number","required":false,"description":"Single-glyph size in px (default 24)."},{"name":"accessibilityLabel","type":"string","required":false,"description":"Accessible name for a MEANINGFUL standalone icon (one that conveys information not repeated in adjacent text, e.g. an icon-only button's glyph). Marks the glyph `role=\"img\"` with this label on web and native."},{"name":"decorative","type":"boolean","required":false,"description":"Mark a DECORATIVE/ornamental glyph (one paired with a text label, a separator chevron, an empty-state illustration) so assistive tech skips it. Hides it via aria-hidden on web and importantForAccessibility on native."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
