/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/description-lists/description-lists.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { DescriptionList } = scope;
  return (
<DescriptionList twoColumn items={[
  { term: "Name", value: "Rachel Chen" },
  { term: "Email", value: "rachel.chen@example.com" }
]} />
  );
}
