/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/description-lists/description-lists.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { DescriptionList } = scope;
  return (
<DescriptionList twoColumn divided items={[
  { term: "Client identifier", value: "clnt_01H2X8K9P3Q7VN4W6R5T0JYMZF", mono: true },
  { term: "Status", value: "Active", status: true }
]} />
  );
}
