/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/description-lists/description-lists.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { DescriptionList } = scope;
  return (
<DescriptionList
card
inline
divided
title="Subscription"
items={[
  { term: "Status", value: "Active", status: true },
  { term: "Seats", value: "12 of 20" },
  { term: "Renews", value: "Mar 1, 2026" }
]}
/>
  );
}
