/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/tabs/tabs.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Tabs } = scope;
  return (
<Tabs tabs={[{ label: "All", badge: "142" }, { label: "Active", badge: "89" }, { label: "Archived", badge: "53" }]} />
  );
}
