/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/board/board.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Board, Chip } = scope;
  return (
<Board
  columns={[
    { id: "todo", label: "To do" },
    { id: "doing", label: "Doing" },
  ]}
  defaultItems={[
    { id: "t1", columnId: "todo", title: "Rotate webhook secrets", menu: [{ label: "Edit", icon: "pencil" }, { label: "Delete", icon: "trash", destructive: true }] },
    { id: "t2", columnId: "doing", title: "SSO rollout", chips: <Chip>identity</Chip> },
  ]}
  onPressItem={(item) => {}}
  onSelectItemMenu={(item, menuItem) => {}}
/>
  );
}
