/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/histogram/histogram.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Chart } = scope;
  return (
<Chart
data={[
  { label: "small", value: 9 },
  { label: "medium", value: 5 },
  { label: "large", value: 2 },
]}
/>
  );
}
