/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/histogram/histogram.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Histogram } = scope;
  return (
<Histogram
  compact
  hideGrid
  values={[4.2, 4.8, 5.1, 4.4, 6.2, 5.5, 4.9, 5.0, 4.6, 7.8, 5.2, 4.7, 5.4, 4.3, 5.8]}
/>
  );
}
