/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/histogram/histogram.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, Histogram } = scope;
  return (
<Container xl>
  <Histogram
  title="Response times"
  label="Latency ms"
  values={[42, 38, 51, 44, 47, 39, 58, 62, 44, 41, 49, 53, 46, 43, 71, 48, 45, 55, 40, 66, 50, 47, 52, 84, 43, 46, 59, 49, 44, 51]}
/>
</Container>
  );
}
