/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/candlestick-chart/candlestick-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, CandlestickChart } = scope;
  return (
<Container xl>
  <CandlestickChart
  title="OLY · 30 sessions"
  labels={["D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10", "D11", "D12", "D13", "D14", "D15", "D16", "D17", "D18", "D19", "D20", "D21", "D22", "D23", "D24", "D25", "D26", "D27", "D28", "D29", "D30"]}
  candles={[
    { open: 182.0, high: 182.2, low: 179.4, close: 181.6 },
    { open: 181.6, high: 182.4, low: 181.1, close: 181.6 },
    { open: 181.6, high: 181.8, low: 179.0, close: 180.9 },
    { open: 180.9, high: 181.9, low: 180.8, close: 180.9 },
    { open: 180.9, high: 181.9, low: 180.0, close: 180.2 },
    { open: 180.2, high: 182.3, low: 179.2, close: 181.0 },
    { open: 181.0, high: 181.5, low: 179.4, close: 180.2 },
    { open: 180.2, high: 182.5, low: 178.8, close: 181.0 },
    { open: 181.0, high: 182.8, low: 178.9, close: 180.1 },
    { open: 180.1, high: 181.4, low: 179.8, close: 179.9 },
    { open: 179.9, high: 181.1, low: 178.5, close: 180.9 },
    { open: 180.9, high: 181.5, low: 179.4, close: 181.2 },
    { open: 181.2, high: 184.1, low: 179.3, close: 182.6 },
    { open: 182.6, high: 183.7, low: 182.1, close: 182.5 },
    { open: 182.5, high: 183.7, low: 180.1, close: 181.8 },
    { open: 181.8, high: 185.1, low: 181.5, close: 183.2 },
    { open: 183.2, high: 183.6, low: 181.4, close: 183.2 },
    { open: 183.2, high: 183.6, low: 180.8, close: 182.7 },
    { open: 182.7, high: 183.5, low: 180.8, close: 182.9 },
    { open: 182.9, high: 185.1, low: 180.2, close: 182.3 },
    { open: 182.3, high: 183.6, low: 181.1, close: 183.1 },
    { open: 183.1, high: 183.6, low: 183.0, close: 183.4 },
    { open: 183.4, high: 185.5, low: 182.3, close: 184.0 },
    { open: 184.0, high: 185.7, low: 181.4, close: 183.1 },
    { open: 183.1, high: 184.8, low: 182.6, close: 183.8 },
    { open: 183.8, high: 185.8, low: 183.2, close: 184.9 },
    { open: 184.9, high: 185.4, low: 183.0, close: 185.4 },
    { open: 185.4, high: 187.3, low: 182.7, close: 184.5 },
    { open: 184.5, high: 185.9, low: 182.5, close: 184.9 },
    { open: 184.9, high: 185.6, low: 183.4, close: 185.4 }
  ]}
  volume={[20, 55, 56, 48, 45, 55, 40, 36, 57, 55, 52, 24, 55, 32, 31, 54, 54, 40, 20, 34, 23, 29, 31, 43, 31, 28, 27, 29, 29, 51]}
  overlays={[{ label: "5-day average", values: [181.6, 181.6, 181.4, 181.2, 181.0, 180.9, 180.6, 180.7, 180.5, 180.4, 180.4, 180.6, 180.9, 181.4, 181.8, 182.3, 182.7, 182.7, 182.8, 182.9, 182.8, 182.9, 183.1, 183.2, 183.5, 183.8, 184.2, 184.3, 184.7, 185.0] }]}
/>
</Container>
  );
}
