/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/skeleton/skeleton.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Skeleton } = scope;
  return (
<View style={{ width: 320, maxWidth: "100%", flexDirection: "column", gap: 6 }}>
  <Skeleton text animate />
  <Skeleton text animate />
  <Skeleton text animate />
</View>
  );
}
