/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/skeleton/skeleton.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Skeleton, Column, Container } = scope;
  return (
<Container xs>
  <Column snug>
    <Skeleton text animate />
    <Skeleton text animate long />
    <Skeleton text animate short />
  </Column>
</Container>
  );
}
