/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/skeleton/skeleton.md
import type { ComponentDocs } from "../../../scope";
import e_atoms_skeleton_example_0 from "./example-0";
import e_atoms_skeleton_example_1 from "./example-1";
import e_atoms_skeleton_example_2 from "./example-2";
import e_atoms_skeleton_example_3 from "./example-3";
import e_atoms_skeleton_example_4 from "./example-4";
import e_atoms_skeleton_example_5 from "./example-5";
import e_atoms_skeleton_dont_0_do from "./dont-0-do";
import e_atoms_skeleton_dont_0_dont from "./dont-0-dont";
import e_atoms_skeleton_dont_1_do from "./dont-1-do";
import e_atoms_skeleton_dont_1_dont from "./dont-1-dont";
import e_atoms_skeleton_dont_2_do from "./dont-2-do";
import e_atoms_skeleton_dont_2_dont from "./dont-2-dont";
import e_atoms_skeleton_dont_3_do from "./dont-3-do";
import e_atoms_skeleton_dont_3_dont from "./dont-3-dont";
import e_atoms_skeleton_dont_4_do from "./dont-4-do";
import e_atoms_skeleton_dont_4_dont from "./dont-4-dont";
import e_atoms_skeleton_dont_5_do from "./dont-5-do";
import e_atoms_skeleton_dont_5_dont from "./dont-5-dont";

export const docs: ComponentDocs = {
  dir: "skeleton",
  category: "atoms",
  examples: [
    { label: "Default", code: "<Skeleton animate />", render: e_atoms_skeleton_example_0 },
    { label: "Avatar", code: "<Skeleton avatar />", render: e_atoms_skeleton_example_1 },
    { label: "Button", code: "<Skeleton button />", render: e_atoms_skeleton_example_2 },
    { label: "Card", code: "<Skeleton card />", render: e_atoms_skeleton_example_3 },
    { label: "List", code: "<Skeleton list />", render: e_atoms_skeleton_example_4 },
    { label: "Table", code: "<Skeleton table />", render: e_atoms_skeleton_example_5 },
  ],
  donts: [
    { title: "text", do: { caption: "Vary the line widths and shorten the last line so it reads like real wrapped text.", code: "<Column snug>\n  <Skeleton text animate />\n  <Skeleton text animate long />\n  <Skeleton text animate short />\n</Column>", render: e_atoms_skeleton_dont_0_do }, dont: { caption: "Three full-width lines read as a solid block, not as a paragraph of prose.", code: "<View style={{ width: 320, maxWidth: \"100%\", flexDirection: \"column\", gap: 6 }}>\n  <Skeleton text animate />\n  <Skeleton text animate />\n  <Skeleton text animate />\n</View>", render: e_atoms_skeleton_dont_0_dont } },
    { title: "avatar", do: { caption: "Match the avatar's circle exactly so the photo drops in with no shift.", code: "<Skeleton avatar animate />", render: e_atoms_skeleton_dont_1_do }, dont: { caption: "A square placeholder for a round avatar snaps shape the instant the image loads.", code: "<View style={{ backgroundColor: tokens.muted, borderRadius: 6, width: 40, height: 40 }} />", render: e_atoms_skeleton_dont_1_dont } },
    { title: "button", do: { caption: "Size the placeholder to the button's real height and width.", code: "<Skeleton button animate />", render: e_atoms_skeleton_dont_2_do }, dont: { caption: "An oversized bar overstates a button and the layout jumps when the real control mounts.", code: "<View style={{ backgroundColor: tokens.muted, width: 320, maxWidth: \"100%\", height: 72, borderRadius: 6 }} />", render: e_atoms_skeleton_dont_2_dont } },
    { title: "card", do: { caption: "Mirror the real layout (avatar circle, text lines) so the swap is seamless.", code: "<Skeleton card animate />", render: e_atoms_skeleton_dont_3_do }, dont: { caption: "A generic block that ignores the content's shape causes a jarring shift when it loads.", code: "<View style={{ backgroundColor: tokens.muted, borderRadius: 6, width: 320, maxWidth: \"100%\", height: 88 }} />", render: e_atoms_skeleton_dont_3_dont } },
    { title: "list", do: { caption: "Repeat a per-row placeholder so the avatar-and-text rhythm matches the loaded list.", code: "<Skeleton list animate />", render: e_atoms_skeleton_dont_4_do }, dont: { caption: "One tall block hides the row rhythm, so the list reflows when each item appears.", code: "<View style={{ backgroundColor: tokens.muted, width: 400, maxWidth: \"100%\", height: 120, borderRadius: 6 }} />", render: e_atoms_skeleton_dont_4_dont } },
    { title: "table", do: { caption: "Lay placeholders out on the real column grid so each cell stays put when it fills in.", code: "<Skeleton table animate />", render: e_atoms_skeleton_dont_5_do }, dont: { caption: "A single rectangle gives no column structure; cells shift sideways once data lands.", code: "<View style={{ backgroundColor: tokens.muted, width: 400, maxWidth: \"100%\", height: 120, borderRadius: 6 }} />", render: e_atoms_skeleton_dont_5_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"SkeletonProps","props":[{"name":"text","type":"boolean","required":false,"description":"Shape (pick one; default is a single text line)."},{"name":"avatar","type":"boolean","required":false,"description":"Shape (pick one; default is a single text line)."},{"name":"button","type":"boolean","required":false,"description":"Shape (pick one; default is a single text line)."},{"name":"card","type":"boolean","required":false,"description":"Shape (pick one; default is a single text line)."},{"name":"list","type":"boolean","required":false,"description":"Shape (pick one; default is a single text line)."},{"name":"table","type":"boolean","required":false,"description":"Shape (pick one; default is a single text line)."},{"name":"small","type":"boolean","required":false,"description":"Size (pick one). Scales the line height and the avatar/button footprint."},{"name":"large","type":"boolean","required":false,"description":"Size (pick one). Scales the line height and the avatar/button footprint."},{"name":"long","type":"boolean","required":false,"description":"A line that runs most of the way across (80%), a mid-paragraph line."},{"name":"short","type":"boolean","required":false,"description":"A short trailing line (60%), the last line of a paragraph."},{"name":"animate","type":"boolean","required":false,"description":"Subtle opacity pulse while content loads."},{"name":"accessibilityLabel","type":"string","required":false,"description":"Screen-reader label announced for the loading placeholder. Defaults to \"Loading\". The placeholder carries a `progressbar` role + busy state so assistive tech announces the pending content (matching Spinner / Progress)."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
