/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/bullet-chart/bullet-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, BulletChart } = scope;
  return (
<Container lg>
  <BulletChart
  title="Budgets"
  compact
  data={[
    { label: "Compute", value: 8200, target: 10000, ranges: [6000, 10000, 14000] },
    { label: "Storage", value: 4100, target: 5000, ranges: [3000, 5000, 8000] },
  ]}
/>
</Container>
  );
}
