/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/bullet-chart/bullet-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { BulletChart } = scope;
  return (
<BulletChart
  success
  data={[
    { label: "Web", value: 34, target: 30 },
    { label: "iOS", value: 18, target: 24 },
    { label: "Android", value: 21, target: 24 },
  ]}
/>
  );
}
