/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/badge/badge.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Badge, BadgeGroup } = scope;
  return (
<BadgeGroup>
  <Badge status success>active</Badge>
  <Badge status warning>degraded</Badge>
  <Badge status error>failed</Badge>
  <Badge status info>syncing</Badge>
  <Badge status neutral>archived</Badge>
</BadgeGroup>
  );
}
