/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/stepper/stepper.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stepper, Row } = scope;
  return (
<Row alignCenter relaxed>
  <Stepper defaultValue={0} min={0} max={5} />
  <Stepper defaultValue={5} min={0} max={5} />
</Row>
  );
}
