/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/image/image.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Image } = scope;
  return (
<Image source={{ uri: "/kira-tanaka.jpg" }} width={120} height={120} />
  );
}
