/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/geo-map/geo-map.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { GeoMap } = scope;
  return (
<GeoMap
title="Signups by city"
points={[
  { label: "London", lat: 51.5072, lng: -0.1276, count: 5170 },
  { label: "Bengaluru", lat: 12.9716, lng: 77.5946, count: 3890 },
  { label: "Sao Paulo", lat: -23.5505, lng: -46.6333, count: 2140 },
  { label: "Lagos", lat: 6.5244, lng: 3.3792, count: 980 },
]}
/>
  );
}
