/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/geo-map/geo-map.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { GeoMap } = scope;
  return (
<GeoMap
  title="Active installs"
  points={[
    { label: "New York", lat: 40.7128, lng: -74.006, count: 6310 },
    { label: "London", lat: 51.5072, lng: -0.1276, count: 5170 },
    { label: "Bengaluru", lat: 12.9716, lng: 77.5946, count: 3890 },
    { label: "Sydney", lat: -33.8688, lng: 151.2093, count: 1260 }
  ]}
/>
  );
}
