/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/geo-map/geo-map.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, GeoMap } = scope;
  return (
<Container xl>
  <GeoMap
  zoomable
  title="Sessions by city"
  points={[
    { label: "San Francisco", lat: 37.7749, lng: -122.4194, count: 4820 },
    { label: "Oakland", lat: 37.8044, lng: -122.2712, count: 1100 },
    { label: "San Jose", lat: 37.3382, lng: -121.8863, count: 2400 },
    { label: "Sacramento", lat: 38.5816, lng: -121.4944, count: 700 },
    { label: "London", lat: 51.5072, lng: -0.1276, count: 5170 },
    { label: "Paris", lat: 48.8566, lng: 2.3522, count: 3100 },
    { label: "Brussels", lat: 50.8503, lng: 4.3517, count: 900 },
    { label: "Amsterdam", lat: 52.3676, lng: 4.9041, count: 1400 },
    { label: "Berlin", lat: 52.52, lng: 13.405, count: 2650 },
    { label: "Tokyo", lat: 35.6895, lng: 139.6917, count: 3110 },
  ]}
/>
</Container>
  );
}
