/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/progress-ring/progress-ring.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { ProgressRing } = scope;
  return (
<ProgressRing value={72} label="Complete" />
  );
}
