/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/progress-ring/progress-ring.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Column, ProgressRing } = scope;
  return (
<Card padded>
  <Column alignCenter>
    <ProgressRing value={81} warning compact label="Budget used" />
  </Column>
</Card>
  );
}
