/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/progress-ring/progress-ring.md
import type { ComponentDocs } from "../../../scope";
import e_charts_progress_ring_example_0 from "./example-0";
import e_charts_progress_ring_example_1 from "./example-1";
import e_charts_progress_ring_example_2 from "./example-2";
import e_charts_progress_ring_example_3 from "./example-3";
import e_charts_progress_ring_dont_0_do from "./dont-0-do";
import e_charts_progress_ring_dont_0_dont from "./dont-0-dont";

export const docs: ComponentDocs = {
  dir: "progress-ring",
  category: "charts",
  examples: [
    { label: "Default", code: "<ProgressRing value={72} label=\"Complete\" />", render: e_charts_progress_ring_example_0 },
    { label: "Success tone", code: "<ProgressRing value={92} success />", render: e_charts_progress_ring_example_1 },
    { label: "Warning tone", code: "<ProgressRing value={81} warning />", render: e_charts_progress_ring_example_2 },
    { label: "Compact", code: "<ProgressRing value={72} compact />", render: e_charts_progress_ring_example_3 },
  ],
  donts: [
    { title: "ProgressRing", do: { caption: "Put a muted track behind the value arc, the percent readout in the ring's center, and the label below the graphic.", code: "<Card padded>\n  <Column alignCenter>\n    <ProgressRing value={72} label=\"Complete\" />\n  </Column>\n</Card>", render: e_charts_progress_ring_dont_0_do }, dont: { caption: "A bordered circle with no track and no readout gives no baseline to read the fill against and no exact value.", code: "<View style={{ borderRadius: 8, borderWidth: 1, borderColor: tokens.border, backgroundColor: tokens.card, padding: 20, maxWidth: 200, alignItems: \"center\" }}>\n  <View style={{ borderRadius: 9999, borderWidth: 10, borderColor: tokens.primary, height: 120, width: 120 }} />\n</View>", render: e_charts_progress_ring_dont_0_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"ProgressRingProps","props":[{"name":"value","type":"number","required":true,"description":"The value to display, 0-100."},{"name":"label","type":"string","required":false,"description":"A short caption beneath the number (e.g. \"Complete\")."},{"name":"primary","type":"boolean","required":false,"description":"several are passed: success > warning > destructive (first match wins)."},{"name":"success","type":"boolean","required":false,"description":"several are passed: success > warning > destructive (first match wins)."},{"name":"warning","type":"boolean","required":false,"description":"several are passed: success > warning > destructive (first match wins)."},{"name":"destructive","type":"boolean","required":false,"description":"several are passed: success > warning > destructive (first match wins)."},{"name":"compact","type":"boolean","required":false,"description":"Density (omit for the default 120 diameter; compact is 96)."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"For sizing/composition only."}]}],
};
