/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/carousel/carousel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Carousel, Card } = scope;
  return (
<Carousel
  items={[
    { key: "one", content: <Card title="Slide 1" /> },
    { key: "two", content: <Card title="Slide 2" /> },
    { key: "three", content: <Card title="Slide 3" /> }
  ]}
/>
  );
}
