/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/carousel/carousel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Carousel, Card } = scope;
  return (
<Carousel
  showArrows
  showDots
  items={[
    { key: "p", content: <Card title="Photos" /> },
    { key: "q", content: <Card title="Albums" /> },
    { key: "r", content: <Card title="Shared" /> }
  ]}
/>
  );
}
