/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/carousel/carousel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Carousel, Card } = scope;
  return (
<Carousel
  defaultIndex={1}
  items={[
    { key: "x", content: <Card title="First" /> },
    { key: "y", content: <Card title="Second" /> },
    { key: "z", content: <Card title="Third" /> }
  ]}
/>
  );
}
