/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/carousel/carousel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Carousel } = scope;
  return (
<Carousel
  loop
  showArrows
  items={[
    { key: "first", content: "Start" },
    { key: "mid", content: "Middle" },
    { key: "last", content: "End" }
  ]}
/>
  );
}
