/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/carousel/carousel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Carousel, Card } = scope;
  return (
<Carousel
  showArrows={false}
  items={[
    { key: "a", content: <Card title="Featured" /> },
    { key: "b", content: <Card title="Popular" /> }
  ]}
/>
  );
}
