/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/carousel/carousel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Carousel } = scope;
  return (
<Carousel
  showArrows
  showDots
  items={[
    { key: "p", content: "Photos" },
    { key: "q", content: "Albums" },
    { key: "r", content: "Shared" }
  ]}
/>
  );
}
