/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/video/video.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Video } = scope;
  return (
<Video source={{ uri: "/video-sample.mp4" }} poster={{ uri: "/video-sample.jpg" }} cover aspectRatio={1} radius="lg" accessibilityLabel="Square crop of the sample clip" />
  );
}
