/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/chart/chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Chart } = scope;
  return (
<Chart
title="Coverage"
horizontal
data={[
  { label: "Atoms", value: 92 },
  { label: "Molecules", value: 78 },
  { label: "Organisms", value: 64 },
  { label: "Charts", value: 85 }
]}
max={100}
/>
  );
}
