/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/chart/chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Chart } = scope;
  return (
<Chart
  stacked
  labels={["acme", "globex", "initech", "umbrella"]}
  series={[
    { label: "Authorization code", values: [1840, 1210, 960, 640] },
    { label: "Client credentials", values: [920, 1480, 340, 1120] },
    { label: "Refresh token", values: [610, 380, 720, 290] }
  ]}
/>
  );
}
