/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/chart/chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Chart, Column } = scope;
  return (
<Column loose>
  <Chart
    success
    data={[
      { label: "Mon", value: 82 },
      { label: "Tue", value: 88 },
      { label: "Wed", value: 91 },
      { label: "Thu", value: 86 },
      { label: "Fri", value: 94 }
    ]}
  />
  <Chart
    destructive
    data={[
      { label: "Mon", value: 14 },
      { label: "Tue", value: 9 },
      { label: "Wed", value: 22 },
      { label: "Thu", value: 12 },
      { label: "Fri", value: 7 }
    ]}
  />
</Column>
  );
}
