/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/chart/chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Chart } = scope;
  return (
<Chart
  labels={["Q1", "Q2", "Q3", "Q4"]}
  series={[
    { label: "Revenue", values: [62, 70, 84, 89] },
    { label: "Costs", values: [41, 48, 55, 59] },
    { label: "Profit", values: [21, 22, 29, 30] }
  ]}
/>
  );
}
