/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/chip/chip.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Row, Chip } = scope;
  return (
<Row>
  <Chip selectable outline defaultSelected>Design</Chip>
  <Chip selectable outline>Engineering</Chip>
</Row>
  );
}
