/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/collapsible/collapsible.md
import type { ComponentDocs } from "../../../scope";
import e_molecules_collapsible_example_0 from "./example-0";
import e_molecules_collapsible_example_1 from "./example-1";
import e_molecules_collapsible_example_2 from "./example-2";
import e_molecules_collapsible_example_3 from "./example-3";
import e_molecules_collapsible_example_4 from "./example-4";
import e_molecules_collapsible_example_5 from "./example-5";
import e_molecules_collapsible_dont_0_do from "./dont-0-do";
import e_molecules_collapsible_dont_0_dont from "./dont-0-dont";

export const docs: ComponentDocs = {
  dir: "collapsible",
  category: "molecules",
  examples: [
    { label: "Default", code: "<Collapsible title=\"Shipping details\">\n  Free 2-day shipping on orders over $50. Delivery in 3 to 5 business days otherwise.\n</Collapsible>", render: e_molecules_collapsible_example_0 },
    { label: "Open by default", code: "<Collapsible title=\"What is Canvas?\" defaultOpen>\n  A universal React Native UI kit that renders natively on iOS and Android and on the web through React Native Web.\n</Collapsible>", render: e_molecules_collapsible_example_1 },
    { label: "Disabled", code: "<Collapsible title=\"Advanced settings (coming soon)\" disabled>\n  Not available yet.\n</Collapsible>", render: e_molecules_collapsible_example_2 },
    { label: "Card surface", code: "<Collapsible card title=\"Shipping details\" defaultOpen>\n  Free 2-day shipping on orders over $50. Delivery in 3 to 5 business days otherwise.\n</Collapsible>", render: e_molecules_collapsible_example_3 },
    { label: "With descriptions", code: "<Collapsible title=\"Notifications\" description=\"Email, push, and digest frequency.\">\n  Choose which events reach your inbox and which stay in the app.\n</Collapsible>", render: e_molecules_collapsible_example_4 },
    { label: "Custom trigger", code: "<Collapsible trigger={<Typography medium>Order #1024, 3 items</Typography>}>\n  Wireless mouse, USB-C cable, laptop stand. Estimated total $84.00.\n</Collapsible>", render: e_molecules_collapsible_example_5 },
  ],
  donts: [
    { do: { caption: "Use one Collapsible to hide a single block of secondary detail behind a clear label, and let the chevron carry the open/closed affordance.", code: "<Collapsible title=\"Returns policy\">\n  30-day returns, no questions asked. Refunds post within 5 business days.\n</Collapsible>", render: e_molecules_collapsible_dont_0_do }, dont: { caption: "Don't reach for a Collapsible when you have several related, peer sections; that is an Accordion's job, and a stack of standalone disclosures loses the single-open coordination.", code: "<View>\n  <Collapsible title=\"Billing\">Manage your plan.</Collapsible>\n  <Collapsible title=\"Team\">Invite teammates.</Collapsible>\n  <Collapsible title=\"Security\">Two-factor authentication.</Collapsible>\n</View>", render: e_molecules_collapsible_dont_0_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"CollapsibleProps","props":[{"name":"title","type":"string","required":false,"description":"The default trigger label text."},{"name":"description","type":"string","required":false,"description":"The muted secondary line under the title in the default trigger anatomy (ignored when a custom `trigger` is given, which owns its own anatomy)."},{"name":"trigger","type":"ReactNode","required":false,"description":"A custom trigger node; if provided, it renders as the pressable's content instead of the `title` text (the chevron still renders alongside)."},{"name":"card","type":"boolean","required":false,"description":"Card surface: wraps the disclosure in an outlined card container with inset header and content (web/Android). On iOS the default Collapsible already renders as the inset-grouped card, so `card` is a no-op there."},{"name":"children","type":"ReactNode","required":true,"description":"The collapsible content. A string renders in the skin's content type; a ReactNode renders as-is."},{"name":"open","type":"boolean","required":false,"description":"Controlled open state. Pair with `onOpenChange`. Omit for uncontrolled."},{"name":"onOpenChange","type":"(open: boolean) => void","required":false,"description":"Called with the next open state whenever the header toggles."},{"name":"defaultOpen","type":"boolean","required":false,"description":"Initial open state for the uncontrolled case (read once, default false)."},{"name":"disabled","type":"boolean","required":false,"description":"A disabled header does not toggle and reads dimmed."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
