/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/collapsible/collapsible.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Collapsible } = scope;
  return (
<Collapsible title="Notifications" description="Email, push, and digest frequency.">
  Choose which events reach your inbox and which stay in the app.
</Collapsible>
  );
}
