/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/data-table/data-table.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { DataTable } = scope;
  return (
<DataTable bordered columns={["Name", "Email", "Status"]} rows={[]} />
  );
}
