/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/data-table/data-table.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { DataTable, MediaObject } = scope;
  return (
<DataTable
  columns={["Member", "Role"]}
  rows={[
    [<MediaObject compact avatar="AJ" title="Alice Johnson" />, "Admin"],
    [<MediaObject compact avatar="BS" title="Bob Smith" />, "Editor"],
    [<MediaObject compact avatar="RC" title="Rachel Chen" />, "Admin"]
  ]}
/>
  );
}
