/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/data-table/data-table.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { DataTable } = scope;
  return (
<DataTable
  stacks
  sortable
  columns={["Setting", "Default", "Description"]}
  rows={[
    ["Session timeout", "30 minutes", "Signs a member out after this long without activity. Shorter timeouts suit shared devices; longer ones suit a personal laptop."],
    ["Password length", "12 characters", "The shortest password a member can choose. Longer minimums resist guessing, and a passphrase meets them easily."],
    ["Recovery codes", "10 codes", "One-time codes a member can use when their authenticator is unavailable. Each code works once."]
  ]}
/>
  );
}
