/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/data-table/data-table.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, DataTable } = scope;
  return (
<Card flat flush style={{ overflow: "hidden" }}>
  <DataTable
    attached
    columns={["Name", "Email", "Role"]}
    rows={[
      ["Alice Johnson", "alice@example.com", "Admin"],
      ["Bob Smith", "bob@example.com", "Editor"],
      ["Rachel Chen", "rachel@example.com", "Admin"]
    ]}
  />
</Card>
  );
}
