/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/range-area-chart/range-area-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, RangeAreaChart } = scope;
  return (
<Container xl>
  <RangeAreaChart
  title="Forecast"
  label="Confidence band"
  labels={["W1", "W2", "W3", "W4"]}
  data={[
    { low: 90, high: 110, mid: 100 },
    { low: 95, high: 125, mid: 108 },
    { low: 100, high: 140, mid: 118 },
    { low: 104, high: 158, mid: 129 },
  ]}
/>
</Container>
  );
}
