/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/range-area-chart/range-area-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, RangeAreaChart } = scope;
  return (
<Container xl>
  <RangeAreaChart
  title="Daily temperature"
  label="Range"
  labels={["Jan", "Feb", "Mar", "Apr", "May", "Jun"]}
  curved
  data={[
    { low: -4, high: 6 },
    { low: -2, high: 9 },
    { low: 2, high: 14 },
    { low: 7, high: 19 },
    { low: 11, high: 24 },
    { low: 15, high: 28 },
  ]}
/>
</Container>
  );
}
