/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/backdrop/backdrop.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Backdrop } = scope;
  return (
<View style={{ height: 220 }}>
  <Backdrop>
    <Backdrop.Gradient
      blobs={[
        { color: "#6366f1", cx: 0.35, cy: 0.35, r: 0.5, o: 0.35, end: 0.62 },
        { color: "#ec4899", cx: 0.7, cy: 0.6, r: 0.44, o: 0.28, end: 0.6 },
      ]}
      size={420}
    />
  </Backdrop>
</View>
  );
}
