/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/tab-bar/tab-bar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, Icon, TabBar } = scope;
  return (
<Stateful initial="home">
  {(active, setActive) => (
    <TabBar
      active={active}
      onSelect={setActive}
      items={[
        { key: "home", label: "Home", icon: (active) => <Icon home size={22} primary={active} muted={!active} /> },
        { key: "search", label: "Search", icon: (active) => <Icon search size={22} primary={active} muted={!active} /> },
        { key: "profile", label: "Profile", icon: (active) => <Icon user size={22} primary={active} muted={!active} /> }
      ]}
    />
  )}
</Stateful>
  );
}
