/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/empty-state/empty-state.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, DataTable, EmptyState, Icon } = scope;
  return (
<Stateful initial={true}>
  {(filtered, setFiltered) => (
    <DataTable
      columns={["Name", "Email", "Role"]}
      rows={filtered ? [] : [
        ["Alice Johnson", "alice@example.com", "Admin"],
        ["Bob Smith", "bob@example.com", "Editor"],
        ["Rachel Chen", "rachel@example.com", "Admin"]
      ]}
      emptyMessage={
        <EmptyState
          icon={<Icon search />}
          title="No results found"
          description="Try adjusting your search filters."
          actionLabel="Clear filters"
          onAction={() => setFiltered(false)}
        />
      }
    />
  )}
</Stateful>
  );
}
