/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/grid/grid.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Card, Typography, Row } = scope;
  return (
<Row wrap snug>
  <View style={{ width: "31%" }}>
    <Card padded>
      <Typography medium>Overview</Typography>
    </Card>
  </View>
  <View style={{ width: "31%" }}>
    <Card padded>
      <Typography medium>Deploys</Typography>
    </Card>
  </View>
  <View style={{ width: "31%" }}>
    <Card padded>
      <Typography medium>Alerts</Typography>
    </Card>
  </View>
</Row>
  );
}
