/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/grid/grid.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography, Grid } = scope;
  return (
<Grid minTileWidth={160} tight>
  <Card padded>
    <Typography small>CPU</Typography>
  </Card>
  <Card padded>
    <Typography small>Memory</Typography>
  </Card>
  <Card padded>
    <Typography small>Disk</Typography>
  </Card>
  <Card padded>
    <Typography small>Network</Typography>
  </Card>
</Grid>
  );
}
