/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/grid/grid.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Grid, GridItem } = scope;
  return (
<Grid minTileWidth={200} columns={3}>
  <GridItem wide>
    <Card title="Latency" />
  </GridItem>
  <Card title="Errors" />
  <Card title="Throughput" />
</Grid>
  );
}
