/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/grid/grid.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Grid } = scope;
  return (
<Grid minTileWidth={200} columns={2}>
  <Card title="Production" />
  <Card title="Staging" />
  <Card title="Preview" />
</Grid>
  );
}
