/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/autocomplete/autocomplete.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Autocomplete } = scope;
  return (
<Autocomplete label="Assigned to" disabled defaultValue="Grace Hopper" options={["Ada Lovelace", "Grace Hopper", "Kira Tanaka"]} />
  );
}
