/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/autocomplete/autocomplete.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Autocomplete, Column, Container } = scope;
  return (
<Column snug>
  <Container xs start><Autocomplete options={["Ada Lovelace", "Grace Hopper"]} placeholder="In an xs Container (320)" /></Container>
  <Container lg start><Autocomplete options={["Ada Lovelace", "Grace Hopper"]} placeholder="In an lg Container (512)" /></Container>
  <Autocomplete options={["Ada Lovelace", "Grace Hopper"]} placeholder="Bare: fills the parent" />
</Column>
  );
}
