/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/radio/radio.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Radio, RadioGroup } = scope;
  return (
<RadioGroup row defaultValue="hobby">
  <Radio value="hobby">Hobby</Radio>
  <Radio value="pro">Pro</Radio>
  <Radio value="enterprise">Enterprise</Radio>
</RadioGroup>
  );
}
