/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/input/input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Input } = scope;
  return (
<Input disabled placeholder="rachel.chen@example.com" />
  );
}
