/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/steps/steps.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Steps, Container } = scope;
  return (
<Container xs>
  <Steps progress current={0} steps={[]} label="Setup progress" value={68} />
</Container>
  );
}
