/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/steps/steps.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Steps } = scope;
  return (
<Steps vertical defaultCurrent={1} steps={[
  { label: "Account created" },
  { label: "Profile setup" },
  { label: "Team invite" },
  { label: "Done" }
]} />
  );
}
