/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/steps/steps.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Steps } = scope;
  return (
<Steps
  stacks
  steps={[{ label: "Account" }, { label: "Profile" }, { label: "Review" }]}
  defaultCurrent={1}
/>
  );
}
