/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/steps/steps.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Steps } = scope;
  return (
<Steps
  vertical
  steps={[
    { label: "Account", description: "Email verified and password set." },
    { label: "Profile", description: "Add your name and avatar." },
    { label: "Review", description: "Invite collaborators." }
  ]}
  defaultCurrent={1}
/>
  );
}
