/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/select/select.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, View, Text, Pressable, Icon } = scope;
  return (
<View>
  <Text style={{ marginBottom: 6, fontSize: 10, lineHeight: 13, fontWeight: "700", letterSpacing: 1.6, textTransform: "uppercase", color: tokens["muted-foreground"] }}>Plan</Text>
  <Pressable style={{ height: 46, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderRadius: 10, borderWidth: 1, borderColor: tokens["field-border"], backgroundColor: tokens["field-fill"], paddingHorizontal: 12 }} accessibilityRole="button">
    <Text style={{ fontSize: 11, lineHeight: 15, fontWeight: "600", color: tokens.foreground }}>Starter</Text>
    <Icon chevronDown muted size={11} decorative />
  </Pressable>
</View>
  );
}
