/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/select/select.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Input, Select, Row, Column, Container } = scope;
  return (
<Container md>
  <Row alignEnd cozy>
    <Column fill>
      <Input label="City" defaultValue="Austin" />
    </Column>
    <Column fill>
      <Select label="State" defaultValue="Texas" options={["Texas", "Oregon"]} />
    </Column>
  </Row>
</Container>
  );
}
