/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/metric-breakdown/metric-breakdown.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, MetricBreakdown } = scope;
  return (
<Card>
  <MetricBreakdown
    plain
    value="25,874"
    label="Requests"
    breakdown={[
      { label: "GET", value: 18248, delta: "+8%" },
      { label: "POST", value: 6104, delta: "+21%" },
      { label: "PATCH", value: 1212, delta: "-2%", down: true },
    ]}
  />
</Card>
  );
}
