/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/view/view.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography, Container } = scope;
  return (
<Container xxs>
  <Card>
    <Typography>A real surface</Typography>
  </Card>
</Container>
  );
}
