/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/gauge/gauge.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Column, Gauge } = scope;
  return (
<Card padded>
  <Column alignCenter>
    <Gauge value={81} warning label="Budget used" />
  </Column>
</Card>
  );
}
