/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/phone-input/phone-input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { PhoneInput, Typography, Column } = scope;
  return (
<Column tight>
  <PhoneInput label="Phone number" defaultCountry="US" defaultValue="(415) 72" />
  <Typography tiny destructive>Invalid phone number.</Typography>
</Column>
  );
}
