/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/phone-input/phone-input.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { PhoneInput, Column } = scope;
  return (
<Column relaxed>
  <PhoneInput small label="Small" placeholder="Add your phone number" />
  <PhoneInput label="Default" placeholder="Add your phone number" />
  <PhoneInput large label="Large" placeholder="Add your phone number" />
</Column>
  );
}
