/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/depth-chart/depth-chart.md
import type { ComponentDocs } from "../../../scope";
import e_charts_depth_chart_example_0 from "./example-0";
import e_charts_depth_chart_example_1 from "./example-1";

export const docs: ComponentDocs = {
  dir: "depth-chart",
  category: "charts",
  examples: [
    { label: "Default", code: "<DepthChart\n  title=\"OLY order book\"\n  bids={[\n    { price: 191.3, size: 80 },\n    { price: 191.15, size: 120 },\n    { price: 191.0, size: 116 },\n    { price: 190.85, size: 118 },\n    { price: 190.7, size: 176 },\n    { price: 190.55, size: 190 },\n    { price: 190.4, size: 210 },\n    { price: 190.25, size: 236 }\n  ]}\n  asks={[\n    { price: 191.6, size: 90 },\n    { price: 191.75, size: 122 },\n    { price: 191.9, size: 110 },\n    { price: 192.05, size: 154 },\n    { price: 192.2, size: 154 },\n    { price: 192.35, size: 210 },\n    { price: 192.5, size: 222 },\n    { price: 192.65, size: 240 }\n  ]}\n/>", render: e_charts_depth_chart_example_0 },
    { label: "Compact", code: "<DepthChart\n  compact\n  bids={[\n    { price: 191.3, size: 90 },\n    { price: 191.15, size: 150 },\n    { price: 191.0, size: 220 },\n    { price: 190.85, size: 310 },\n    { price: 190.7, size: 420 }\n  ]}\n  asks={[\n    { price: 191.6, size: 110 },\n    { price: 191.75, size: 180 },\n    { price: 191.9, size: 260 },\n    { price: 192.05, size: 350 },\n    { price: 192.2, size: 470 }\n  ]}\n/>", render: e_charts_depth_chart_example_1 },
  ],
  donts: [

  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"DepthChartProps","props":[{"name":"bids","type":"DepthLevel[]","required":true,"description":"Bid levels (any order; sorted internally)."},{"name":"asks","type":"DepthLevel[]","required":true,"description":"Ask levels (any order; sorted internally)."},{"name":"title","type":"string","required":false,"description":"Optional heading shown above the plot."},{"name":"compact","type":"boolean","required":false,"description":"Density (omit for the default plot size)."},{"name":"hideLegend","type":"boolean","required":false,"description":"Furniture visibility."},{"name":"hideGrid","type":"boolean","required":false,"description":"Furniture visibility."},{"name":"hideAxes","type":"boolean","required":false,"description":"Furniture visibility."},{"name":"formatValue","type":"(v: number) => string","required":false,"description":"Formats tick labels and accessible values (data formatting, not styling)."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
