/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Avatar, AvatarGroup } = scope;
  return (
<AvatarGroup small max={4} total={16}>
  <Avatar name="Ada Okafor" />
  <Avatar name="Rachel Chen" />
  <Avatar name="Liang Bao" />
  <Avatar name="Kira Tran" />
</AvatarGroup>
  );
}
