/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Avatar, Dropdown } = scope;
  return (
<Dropdown items={[{ label: "Your profile" }, { label: "Sign out" }]}>
  <Avatar small name="MA" />
</Dropdown>
  );
}
