/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/avatar/avatar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { AvatarMenu } = scope;
  return (
<AvatarMenu
  compact
  name="Marcus Allen"
  email="admin@example.com"
  src="/marcus-allen.jpg"
  items={[
    { label: "Profile", icon: "user" },
    { label: "Settings", icon: "settings" },
    { label: "Sign out", icon: "logOut", destructive: true, separatorBefore: true }
  ]}
/>
  );
}
