/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/breadcrumb/breadcrumb.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Breadcrumb } = scope;
  return (
<Breadcrumb items={["Projects", "Identity Platform", "Settings"]} />
  );
}
