/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/radial-bar-chart/radial-bar-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { RadialBarChart } = scope;
  return (
<RadialBarChart
  label="Platform activation"
  max={100}
  data={[
    { label: "iOS", value: 64 },
    { label: "Android", value: 48 },
    { label: "Web", value: 82 }
  ]}
/>
  );
}
