/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/radial-bar-chart/radial-bar-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { RadialBarChart } = scope;
  return (
<RadialBarChart
  compact
  hideLegend
  data={[
    { label: "Q1", value: 92 },
    { label: "Q2", value: 71 }
  ]}
/>
  );
}
