/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/radial-bar-chart/radial-bar-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { RadialBarChart } = scope;
  return (
<RadialBarChart
  defaultSelected={1}
  data={[
    { label: "Hot", value: 420 },
    { label: "Warm", value: 260 },
    { label: "Cold", value: 890 }
  ]}
/>
  );
}
