/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/radial-bar-chart/radial-bar-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Container, RadialBarChart } = scope;
  return (
<Container xxxs>
  <Card padded>
    <RadialBarChart
      label="Quota"
      compact
      hideLegend
      data={[
        { label: "Q1", value: 92 },
        { label: "Q2", value: 71 },
      ]}
      max={100}
    />
  </Card>
</Container>
  );
}
