/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/radial-bar-chart/radial-bar-chart.md
import type { ComponentDocs } from "../../../scope";
import e_charts_radial_bar_chart_example_0 from "./example-0";
import e_charts_radial_bar_chart_example_1 from "./example-1";
import e_charts_radial_bar_chart_example_2 from "./example-2";
import e_charts_radial_bar_chart_dont_0_do from "./dont-0-do";
import e_charts_radial_bar_chart_dont_0_dont from "./dont-0-dont";

export const docs: ComponentDocs = {
  dir: "radial-bar-chart",
  category: "charts",
  examples: [
    { label: "Default", code: "<RadialBarChart\n  label=\"Platform activation\"\n  max={100}\n  data={[\n    { label: \"iOS\", value: 64 },\n    { label: \"Android\", value: 48 },\n    { label: \"Web\", value: 82 }\n  ]}\n/>", render: e_charts_radial_bar_chart_example_0 },
    { label: "Compact, no legend", code: "<RadialBarChart\n  compact\n  hideLegend\n  data={[\n    { label: \"Q1\", value: 92 },\n    { label: \"Q2\", value: 71 }\n  ]}\n/>", render: e_charts_radial_bar_chart_example_1 },
    { label: "Inspected", code: "<RadialBarChart\n  defaultSelected={1}\n  data={[\n    { label: \"Hot\", value: 420 },\n    { label: \"Warm\", value: 260 },\n    { label: \"Cold\", value: 890 }\n  ]}\n/>", render: e_charts_radial_bar_chart_example_2 },
  ],
  donts: [
    { title: "RadialBarChart", do: { caption: "Compare attainment on rings that share one sweep maximum, with the values in the legend.", code: "<Card padded>\n  <RadialBarChart\n    label=\"Platform activation\"\n    data={[\n      { label: \"iOS\", value: 64 },\n      { label: \"Web\", value: 82 },\n    ]}\n    max={100}\n  />\n</Card>", render: e_charts_radial_bar_chart_dont_0_do }, dont: { caption: "Rings encoding shares of a whole belong on PieChart; nested rings without a shared maximum cannot be compared by eye.", code: "<Card padded>\n  <RadialBarChart\n    label=\"Traffic split\"\n    data={[\n      { label: \"Direct\", value: 60 },\n      { label: \"Search\", value: 40 },\n    ]}\n  />\n</Card>", render: e_charts_radial_bar_chart_dont_0_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"RadialBarChartProps","props":[{"name":"data","type":"StackedSegment[]","required":true,"description":"One ring per entry, inner to outer."},{"name":"label","type":"string","required":false,"description":"What the rings measure (e.g. \"Platform activation\"); leads the accessible name."},{"name":"max","type":"number","required":false,"description":"The value of a full sweep. Defaults to the largest entry."},{"name":"compact","type":"boolean","required":false,"description":"Density (omit for the default 160 disc; compact is 120)."},{"name":"hideLegend","type":"boolean","required":false,"description":"Hide the value legend (the accessible name still carries every value)."},{"name":"formatValue","type":"(v: number) => string","required":false,"description":"Formats legend values (data formatting, not styling)."},{"name":"selected","type":"number | null","required":false,"description":"Press-to-inspect: the selected ring index (controlled). Pass null for none."},{"name":"defaultSelected","type":"number","required":false,"description":"Press-to-inspect: the initially selected ring (uncontrolled)."},{"name":"onSelect","type":"(index: number | null) => void","required":false,"description":"Fired when a press selects a ring (or clears it with null)."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"For sizing/composition only."}]}],
};
