/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/stacked-lists/stacked-lists.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, StackedList } = scope;
  return (
<StackedList
  card
  title="Team members"
  action={<Button ghost small>Invite</Button>}
  items={[
    { name: "Rachel Chen", detail: "Engineering Lead" },
    { name: "Ada Lovelace", detail: "Staff Engineer" }
  ]}
/>
  );
}
