/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/uptime-bar/uptime-bar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, UptimeBar } = scope;
  return (
<Container lg>
  <UptimeBar
  label="API uptime"
  caption="99.98% uptime"
  startLabel="90 days ago"
  endLabel="Today"
  periods={Array.from({ length: 90 }, (_, i) =>
    i === 61 ? { down: true } : i === 62 || i === 78 ? { degraded: true } : {},
  )}
/>
</Container>
  );
}
