/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/uptime-bar/uptime-bar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, UptimeBar } = scope;
  return (
<Container lg>
  <UptimeBar
  label="CDN uptime"
  compact
  periods={Array.from({ length: 60 }, (_, i) => (i === 40 ? { degraded: true } : {}))}
/>
</Container>
  );
}
