/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography, Column, Container } = scope;
  return (
<Container xs>
  <Column tight>
    <Typography h3>About Canvas</Typography>
    <Typography body>Canvas is a universal React Native UI kit for building consistent product interfaces.</Typography>
  </Column>
</Container>
  );
}
