/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Typography, Container } = scope;
  return (
<Container xs>
  <Typography body>
    Payment due May 31. 
    <Typography body primary underline>View invoices</Typography>
  </Typography>
</Container>
  );
}
