/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography, Container } = scope;
  return (
<Container xs>
  <Typography h3>Canvas is a universal React Native UI kit for building consistent product interfaces.</Typography>
</Container>
  );
}
