/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography, Column } = scope;
  return (
<Column flush>
  <Typography lead tightLeading>Canvas</Typography>
  <Typography tiny tightLeading>design system</Typography>
</Column>
  );
}
