/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/checkbox/checkbox.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Checkbox, Column } = scope;
  return (
<Column>
  <Checkbox small defaultChecked>Small</Checkbox>
  <Checkbox defaultChecked>Default</Checkbox>
  <Checkbox large defaultChecked>Large</Checkbox>
</Column>
  );
}
