/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/box-plot/box-plot.md
import type { ComponentDocs } from "../../../scope";
import e_charts_box_plot_example_0 from "./example-0";
import e_charts_box_plot_example_1 from "./example-1";
import e_charts_box_plot_example_2 from "./example-2";
import e_charts_box_plot_dont_0_do from "./dont-0-do";
import e_charts_box_plot_dont_0_dont from "./dont-0-dont";

export const docs: ComponentDocs = {
  dir: "box-plot",
  category: "charts",
  examples: [
    { label: "Default", code: "<BoxPlot\n  title=\"Latency by region\"\n  data={[\n    { label: \"us-east\", values: [42, 38, 51, 44, 47, 39, 96] },\n    { label: \"eu-west\", values: [55, 61, 58, 64, 57, 63] },\n    { label: \"ap-south\", values: [71, 78, 74, 83, 76, 124] },\n  ]}\n/>", render: e_charts_box_plot_example_0 },
    { label: "Compact", code: "<BoxPlot\n  compact\n  data={[\n    { label: \"A\", values: [3.1, 3.4, 3.2, 3.8, 3.5, 3.3, 3.9, 3.6] },\n    { label: \"B\", values: [4.2, 4.6, 4.4, 5.1, 4.8, 4.5, 5.4, 4.9] },\n  ]}\n/>", render: e_charts_box_plot_example_1 },
    { label: "Inspected", code: "<BoxPlot\n  defaultSelected={1}\n  data={[\n    { label: \"Mon\", values: [2, 4, 3, 5, 4, 3, 6] },\n    { label: \"Wed\", values: [3, 6, 5, 8, 6, 5, 9] },\n    { label: \"Fri\", values: [5, 9, 7, 12, 9, 8, 22] },\n  ]}\n/>", render: e_charts_box_plot_example_2 },
  ],
  donts: [
    { title: "BoxPlot", do: { caption: "Compare distributions with the full five-number anatomy: box, whiskers, median, outliers.", code: "<BoxPlot\ntitle=\"Latency by region\"\ndata={[\n  { label: \"us-east\", values: [42, 38, 51, 44, 47, 39, 58, 44, 41, 49, 96] },\n  { label: \"eu-west\", values: [55, 61, 58, 64, 57, 63, 59, 66, 60, 62] },\n]}\n/>", render: e_charts_box_plot_dont_0_do }, dont: { caption: "A bar of averages hides the spread and the outliers, which are the point of comparing distributions.", code: "<Chart\ndata={[\n  { label: \"us-east\", value: 46 },\n  { label: \"eu-west\", value: 61 },\n]}\n/>", render: e_charts_box_plot_dont_0_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"BoxPlotProps","props":[{"name":"data","type":"BoxSample[]","required":true,"description":"One box per category, in order."},{"name":"title","type":"string","required":false,"description":"Optional heading shown above the plot."},{"name":"success","type":"boolean","required":false,"description":"Tone (pick one; default primary). Precedence: success > destructive."},{"name":"destructive","type":"boolean","required":false,"description":"Tone (pick one; default primary). Precedence: success > destructive."},{"name":"compact","type":"boolean","required":false,"description":"Density (omit for the default plot size)."},{"name":"hideGrid","type":"boolean","required":false,"description":"Furniture visibility."},{"name":"hideAxes","type":"boolean","required":false,"description":"Furniture visibility."},{"name":"formatValue","type":"(v: number) => string","required":false,"description":"Formats tick labels, the flag, and the accessible name."},{"name":"selected","type":"number | null","required":false,"description":"Scrub-to-inspect: the selected category index (controlled). Pass null for none."},{"name":"defaultSelected","type":"number","required":false,"description":"Scrub-to-inspect: the initially selected category (uncontrolled)."},{"name":"onSelect","type":"(index: number | null) => void","required":false,"description":"Fired when a press/scrub selects a category (or clears it with null)."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
