/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/box-plot/box-plot.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Chart, Container } = scope;
  return (
<Container xl>
  <Chart
  data={[
    { label: "us-east", value: 46 },
    { label: "eu-west", value: 61 },
  ]}
/>
</Container>
  );
}
