/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/box-plot/box-plot.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { BoxPlot } = scope;
  return (
<BoxPlot
title="Latency by region"
data={[
  { label: "us-east", values: [42, 38, 51, 44, 47, 39, 58, 44, 41, 49, 96] },
  { label: "eu-west", values: [55, 61, 58, 64, 57, 63, 59, 66, 60, 62] },
  { label: "ap-south", values: [71, 78, 74, 83, 76, 80, 75, 88, 79, 124] },
]}
/>
  );
}
