/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/feeds/feeds.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Feed } = scope;
  return (
<Feed
  items={[
    { actor: "Rachel Chen", action: "approved the request", time: "2 hours ago" },
    { actor: "Ada Lovelace", action: "merged", target: "release/4.2", time: "5 hours ago" },
    { actor: "System", action: "created the project", time: "3 days ago" }
  ]}
/>
  );
}
