/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/molecules/feeds/feeds.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Feed } = scope;
  return (
<Feed
  items={[
    { icon: "shieldCheck", actor: "System", action: "rotated the signing key", time: "12 minutes ago" },
    { icon: "userPlus", actor: "Rachel Chen", action: "invited a teammate", time: "2 hours ago" },
    { icon: "gitMerge", actor: "Ada Lovelace", action: "merged a release", time: "1 day ago" }
  ]}
/>
  );
}
