/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/radar-chart/radar-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Container, RadarChart } = scope;
  return (
<Container lg>
  <RadarChart
  axes={["Jan", "Feb", "Mar", "Apr", "May", "Jun"]}
  series={[{ label: "Revenue", values: [4, 5, 6, 7, 8, 9] }]}
/>
</Container>
  );
}
