/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/radar-chart/radar-chart.md
import type { ComponentDocs } from "../../../scope";
import e_charts_radar_chart_example_0 from "./example-0";
import e_charts_radar_chart_example_1 from "./example-1";
import e_charts_radar_chart_example_2 from "./example-2";
import e_charts_radar_chart_dont_0_do from "./dont-0-do";
import e_charts_radar_chart_dont_0_dont from "./dont-0-dont";

export const docs: ComponentDocs = {
  dir: "radar-chart",
  category: "charts",
  examples: [
    { label: "Default", code: "<RadarChart\n  title=\"Candidate comparison\"\n  axes={[\"Coding\", \"Design\", \"Comms\", \"Ops\", \"Product\"]}\n  series={[\n    { label: \"Casey\", values: [8, 6, 9, 5, 7] },\n    { label: \"Jordan\", values: [6, 9, 7, 8, 5] },\n  ]}\n/>", render: e_charts_radar_chart_example_0 },
    { label: "Single series, toned", code: "<RadarChart\n  success\n  axes={[\"Latency\", \"Uptime\", \"Errors\", \"Cost\", \"Coverage\"]}\n  series={[{ label: \"API\", values: [7, 9, 8, 6, 7] }]}\n/>", render: e_charts_radar_chart_example_1 },
    { label: "Compact, no grid", code: "<RadarChart\ncompact\nhideGrid\naxes={[\"Spd\", \"Pwr\", \"Def\", \"Mag\", \"Luck\", \"HP\"]}\nseries={[{ label: \"Build A\", values: [12, 18, 9, 15, 7, 14] }]}\n/>", render: e_charts_radar_chart_example_2 },
  ],
  donts: [
    { title: "RadarChart", do: { caption: "Compare a small number of profiles over the same axes, on one shared scale.", code: "<RadarChart\ntitle=\"Candidate comparison\"\naxes={[\"Coding\", \"Design\", \"Comms\", \"Ops\", \"Product\"]}\nseries={[\n  { label: \"Casey\", values: [8, 6, 9, 5, 7] },\n  { label: \"Jordan\", values: [6, 9, 7, 8, 5] },\n]}\nmax={10}\n/>", render: e_charts_radar_chart_dont_0_do }, dont: { caption: "Radar axes are unordered categories; a time series belongs on a LineChart, where the x axis carries the order.", code: "<RadarChart\naxes={[\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", \"Jun\"]}\nseries={[{ label: \"Revenue\", values: [4, 5, 6, 7, 8, 9] }]}\n/>", render: e_charts_radar_chart_dont_0_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"RadarChartProps","props":[{"name":"axes","type":"string[]","required":true,"description":"Spoke labels, clockwise from 12 o'clock."},{"name":"series","type":"ChartSeries[]","required":true,"description":"One polygon per series; values aligned to `axes` by index."},{"name":"title","type":"string","required":false,"description":"Optional heading shown above the plot."},{"name":"max","type":"number","required":false,"description":"Outer-ring maximum. Defaults to a nice bound above the data max."},{"name":"success","type":"boolean","required":false,"description":"success > destructive."},{"name":"destructive","type":"boolean","required":false,"description":"success > destructive."},{"name":"compact","type":"boolean","required":false,"description":"Density (omit for the default plot size)."},{"name":"hideLegend","type":"boolean","required":false,"description":"Hide the series legend (multi-series charts show one by default)."},{"name":"hideGrid","type":"boolean","required":false,"description":"Hide the rings and spokes (the labels always render)."},{"name":"formatValue","type":"(v: number) => string","required":false,"description":"Formats accessible values (data formatting, not styling)."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
