/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/reveal/reveal.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Reveal, RevealGroup, Typography, Row, Container } = scope;
  return (
<Row cozy wrap>
  <RevealGroup>
    <Reveal fromBelow>
      <Container xxxs>
        <Card padded>
          <Typography small semibold>Rises</Typography>
        </Card>
      </Container>
    </Reveal>
    <Reveal fromBelow>
      <Container xxxs>
        <Card padded>
          <Typography small semibold>Rises</Typography>
        </Card>
      </Container>
    </Reveal>
  </RevealGroup>
</Row>
  );
}
