/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/reveal/reveal.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Reveal, Typography, Row, Container } = scope;
  return (
<Row cozy wrap>
  <Reveal>
    <Container xxxs>
      <Card padded>
        <Typography small semibold>First</Typography>
      </Card>
    </Container>
  </Reveal>
  <Reveal>
    <Container xxxs>
      <Card padded>
        <Typography small semibold>Second</Typography>
      </Card>
    </Container>
  </Reveal>
  <Reveal>
    <Container xxxs>
      <Card padded>
        <Typography small semibold>Third</Typography>
      </Card>
    </Container>
  </Reveal>
</Row>
  );
}
