/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/reveal/reveal.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Reveal, Typography } = scope;
  return (
<Reveal fromRight>
  <Card>
    <Typography>Slides in from the right</Typography>
  </Card>
</Reveal>
  );
}
