/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/reveal/reveal.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Reveal, Typography, Container } = scope;
  return (
<Reveal brisk>
  <Container xs>
    <Card padded>
      <Typography small semibold>Arrives faster</Typography>
    </Card>
  </Container>
</Reveal>
  );
}
