/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/reveal/reveal.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Reveal, Typography, Column } = scope;
  return (
<Reveal>
  <Card padded>
    <Column tight>
      <Typography h4 semibold>Built for scroll</Typography>
      <Typography small muted>This card rose into place when it reached the viewport.</Typography>
    </Column>
  </Card>
</Reveal>
  );
}
