/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/calendar/calendar.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Calendar } = scope;
  return (
<Calendar
  range
  month="May 2026"
  today={23}
  daysInMonth={31}
  startWeekday={4}
  defaultRangeStart={14}
  defaultRangeEnd={20}
/>
  );
}
