/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/textarea/textarea.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Textarea } = scope;
  return (
<Textarea label="Description" rows={3} value="This is a longer description that runs past one line and stays readable." />
  );
}
