/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/textarea/textarea.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Textarea, Column, Container } = scope;
  return (
<Column>
  <Textarea xs start rows={2} placeholder="xs step, pinned to the start (320)" />
  <Textarea lg start rows={2} placeholder="lg step, pinned to the start (512)" />
  <Container lg start><Textarea rows={2} placeholder="Bare, in an lg Container: fills it (512)" /></Container>
</Column>
  );
}
