/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/textarea/textarea.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Card, Divider, Textarea, Row } = scope;
  return (
<Card flat flush style={{ overflow: "hidden" }}>
  <Row tight padTight>
    <Button ghost small>B</Button>
    <Button ghost small>I</Button>
  </Row>
  <Divider />
  <Textarea flush placeholder="Leave a comment…" />
</Card>
  );
}
