/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/button/button.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Icon } = scope;
  return (
<Button iconLeft={<Icon plus primaryForeground size={16} />}>Save changes</Button>
  );
}
