/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/heatmap/heatmap.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Heatmap } = scope;
  return (
<Heatmap
  calendar
  label="Contribution activity"
  values={Array.from({ length: 371 }, (_, i) => {
    const noise = Math.sin(i * 12.9898) * 43758.5453;
    const r = noise - Math.floor(noise);
    const value = r < 0.5 ? 0 : (r - 0.5) / 0.5;
    return { value, count: Math.round(value * 14), date: new Date(Date.UTC(2025, 6, 6 + i)).toISOString().slice(0, 10) };
  })}
/>
  );
}
