/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Column } = scope;
  return (
<Column>
  <Button primary>Save</Button>
  <Button ghost>Cancel</Button>
</Column>
  );
}
