/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography, Row, Column } = scope;
  return (
<Row>
  <Column span={8}>
    <Card>
      <Typography medium>Eight of twelve</Typography>
    </Card>
  </Column>
  <Column span={4}>
    <Card>
      <Typography medium>Four</Typography>
    </Card>
  </Column>
</Row>
  );
}
