/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Typography, Row, Column } = scope;
  return (
<Row between alignEnd wrap>
  <Column tight shrink>
    <Typography h3>Dashboard</Typography>
    <Typography small muted>Identity platform overview. Each widget reports its own window.</Typography>
  </Column>
  <Button outline small>Export</Button>
</Row>
  );
}
