/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography, Row, Column } = scope;
  return (
<Row stacks>
  <Column span={6}>
    <Card>
      <Typography medium>Left</Typography>
    </Card>
  </Column>
  <Column span={6}>
    <Card>
      <Typography medium>Right</Typography>
    </Card>
  </Column>
</Row>
  );
}
