/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Input, Row } = scope;
  return (
<Row stacks>
  <Input placeholder="Search runs" />
  <Button primary>New run</Button>
</Row>
  );
}
