/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/layout/layout.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Typography, Row, Column } = scope;
  return (
<Row snug>
  <Column span={8}>
    <Card padded>
      <Typography medium>Content</Typography>
      <Typography small muted>Eight of twelve columns.</Typography>
    </Card>
  </Column>
  <Column span={4}>
    <Card padded>
      <Typography medium>Aside</Typography>
      <Typography small muted>Four of twelve.</Typography>
    </Card>
  </Column>
</Row>
  );
}
