/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/text/text.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, Text, Container } = scope;
  return (
<Container xxs>
  <Text numberOfLines={1} style={{ color: tokens.foreground }}>
    This single line is clipped with an ellipsis when it overflows its container.
  </Text>
</Container>
  );
}
