/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/qrcode/qrcode.md
import type { ComponentDocs } from "../../../scope";
import e_atoms_qrcode_example_0 from "./example-0";
import e_atoms_qrcode_example_1 from "./example-1";
import e_atoms_qrcode_example_2 from "./example-2";
import e_atoms_qrcode_dont_0_do from "./dont-0-do";
import e_atoms_qrcode_dont_0_dont from "./dont-0-dont";

export const docs: ComponentDocs = {
  dir: "qrcode",
  category: "atoms",
  examples: [
    { label: "Default", code: "<QRCode value=\"https://canvas.nannier.com\" />", render: e_atoms_qrcode_example_0 },
    { label: "Small", code: "<QRCode value=\"https://canvas.nannier.com\" small />", render: e_atoms_qrcode_example_1 },
    { label: "Large", code: "<QRCode value=\"https://canvas.nannier.com\" large />", render: e_atoms_qrcode_example_2 },
  ],
  donts: [
    { title: "Keep it scannable", do: { caption: "Leave the fixed dark-on-white card in place so the code stays high-contrast for any camera.", code: "<QRCode value=\"https://canvas.nannier.com\" />", render: e_atoms_qrcode_dont_0_do }, dont: { caption: "Shrinking a data-dense value to the small size drops the modules below a reliably scannable density.", code: "<QRCode value=\"https://canvas.nannier.com/get/the/app?ref=docs&utm=homepage&v=2\" small />", render: e_atoms_qrcode_dont_0_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"QRCodeProps","props":[{"name":"value","type":"string","required":true,"description":"The string to encode: a URL, plain text, a token, etc."},{"name":"small","type":"boolean","required":false,"description":"A compact 96px code."},{"name":"large","type":"boolean","required":false,"description":"A large 200px code."},{"name":"accessibilityLabel","type":"string","required":false,"description":"Spoken equivalent for screen readers. A QR code is camera-only content, so without a label assistive tech announces nothing. Defaults to `QR code encoding ${value}`; pass a generic label (e.g. \"QR code\") when surfacing the raw value is undesirable."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"Composition within a parent only, never a restyle hook and never a width: the parent layout container provides the bounds."}]}],
};
