/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/toast/toast.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { WithToast, AppScreen, Button, ToastProvider, useToast } = scope;
  return (
<AppScreen>
  <ToastProvider>
    <WithToast hook={useToast}>
      {({ toast }) => <Button onPress={() => toast({ message: "Profile updated" })}>Show toast</Button>}
    </WithToast>
  </ToastProvider>
</AppScreen>
  );
}
