/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/toast/toast.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Toast } = scope;
  return (
<Toast destructive message="Upload failed" />
  );
}
