/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/progress/progress.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Progress, Column, Container } = scope;
  return (
<Column snug>
  <Container xs start><Progress value={0.6}>In an xs Container (320)</Progress></Container>
  <Container lg start><Progress value={0.6}>In an lg Container (512)</Progress></Container>
  <Progress value={0.6}>Bare: fills the parent</Progress>
</Column>
  );
}
