/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/progress/progress.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Progress, Column, Container } = scope;
  return (
<Column snug>
  <Progress xs start value={0.6}>xs step, pinned to the start (320)</Progress>
  <Progress lg start value={0.6}>lg step, pinned to the start (512)</Progress>
  <Container lg start><Progress value={0.6}>Bare, in an lg Container: fills it (512)</Progress></Container>
</Column>
  );
}
