/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/emblem/emblem.md
import type { ComponentDocs } from "../../../scope";
import e_atoms_emblem_example_0 from "./example-0";
import e_atoms_emblem_example_1 from "./example-1";
import e_atoms_emblem_example_2 from "./example-2";
import e_atoms_emblem_example_3 from "./example-3";
import e_atoms_emblem_example_4 from "./example-4";
import e_atoms_emblem_dont_0_do from "./dont-0-do";
import e_atoms_emblem_dont_0_dont from "./dont-0-dont";

export const docs: ComponentDocs = {
  dir: "emblem",
  category: "atoms",
  examples: [
    { label: "Default", code: "<Emblem>\n  <Icon shield />\n</Emblem>", render: e_atoms_emblem_example_0 },
    { label: "Tones", code: "<Row snug>\n  <Emblem primary><Icon shield /></Emblem>\n  <Emblem success><Icon check /></Emblem>\n  <Emblem warning><Icon circleAlert /></Emblem>\n  <Emblem destructive><Icon trash /></Emblem>\n  <Emblem muted><Icon bell /></Emblem>\n</Row>", render: e_atoms_emblem_example_1 },
    { label: "Sizes", code: "<Row snug alignCenter>\n  <Emblem small><Icon bell /></Emblem>\n  <Emblem><Icon bell /></Emblem>\n  <Emblem large><Icon bell /></Emblem>\n</Row>", render: e_atoms_emblem_example_2 },
    { label: "Monogram", code: "<Emblem label=\"U\" />", render: e_atoms_emblem_example_3 },
    { label: "Circle", code: "<Emblem circle>\n  <Icon check />\n</Emblem>", render: e_atoms_emblem_example_4 },
  ],
  donts: [
    { title: "Surface", do: { caption: "Use Emblem so the tint and icon color stay in sync from one tone prop.", code: "<Emblem primary>\n  <Icon shield />\n</Emblem>", render: e_atoms_emblem_dont_0_do }, dont: { caption: "Hand-compose the tinted square with raw `borderRadius`, `backgroundColor`, and padding.", code: "<View style={{ height: 40, width: 40, alignItems: \"center\", justifyContent: \"center\", borderRadius: 8, backgroundColor: \"rgba(79,70,229,0.1)\" }}>\n  <Icon shield primary />\n</View>", render: e_atoms_emblem_dont_0_dont } },
  ],
  // Extracted from the component's exported `*Props` interfaces by
  // tools/docgen/extract-props.ts (the TypeScript checker).
  props: [{"name":"EmblemProps","props":[{"name":"children","type":"ReactNode","required":false,"description":"A single `<Icon />` element; Emblem tints it to match the tone."},{"name":"label","type":"string","required":false,"description":"A monogram letter (or two) instead of an icon, painted in the tone color."},{"name":"primary","type":"boolean","required":false,"description":"Tone (pick one; default `muted`). Sets the tinted surface and the icon color."},{"name":"destructive","type":"boolean","required":false,"description":"Tone (pick one; default `muted`). Sets the tinted surface and the icon color."},{"name":"success","type":"boolean","required":false,"description":"Tone (pick one; default `muted`). Sets the tinted surface and the icon color."},{"name":"warning","type":"boolean","required":false,"description":"Tone (pick one; default `muted`). Sets the tinted surface and the icon color."},{"name":"muted","type":"boolean","required":false,"description":"Tone (pick one; default `muted`). Sets the tinted surface and the icon color."},{"name":"small","type":"boolean","required":false,"description":"Size (pick one; default medium)."},{"name":"large","type":"boolean","required":false,"description":"Size (pick one; default medium)."},{"name":"circle","type":"boolean","required":false,"description":"Circle instead of the default rounded square."},{"name":"testID","type":"string","required":false,"description":"E2E hook forwarded to the root element."},{"name":"style","type":"LayoutStyle","required":false,"description":"For layout composition only (not styling): the tint, radius, and size come from props."}]}],
};
