/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/emblem/emblem.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Icon, Row, Emblem } = scope;
  return (
<Row snug>
  <Emblem primary><Icon shield /></Emblem>
  <Emblem success><Icon check /></Emblem>
  <Emblem warning><Icon circleAlert /></Emblem>
  <Emblem destructive><Icon trash /></Emblem>
  <Emblem muted><Icon bell /></Emblem>
</Row>
  );
}
