/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/button-group/button-group.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { ButtonGroup } = scope;
  return (
<ButtonGroup split items={["Save"]} menu={["Save as draft", "Save and close", "Save a copy"]} />
  );
}
